// Generated by scripts/refactor_catalan_map.py — do not edit manually.
import type { DialectZone } from "./accentOracleClient";

export interface ComarcaMapEntry {
  id: string;
  slug: string;
  dialectGroup: string;
  macroDialect: DialectZone;
  centroidX: number;
  centroidY: number;
}

export const COMARCA_MAP_META: ComarcaMapEntry[] = [
  { id: "comarca-vielha", slug: "vielha", dialectGroup: "ca-nwestern", macroDialect: "northwestern", centroidX: 467.46, centroidY: 156.44 },
  { id: "comarca-pallars-sobira", slug: "pallars-sobira", dialectGroup: "ca-nwestern", macroDialect: "northwestern", centroidX: 516.88, centroidY: 194.19 },
  { id: "comarca-alta-ribagorca", slug: "alta-ribagorca", dialectGroup: "ca-nwestern", macroDialect: "northwestern", centroidX: 466.63, centroidY: 205.65 },
  { id: "comarca-cerdanya", slug: "cerdanya", dialectGroup: "ca-nwestern", macroDialect: "northwestern", centroidX: 602.25, centroidY: 218.27 },
  { id: "comarca-alt-urgell", slug: "alt-urgell", dialectGroup: "ca-nwestern", macroDialect: "northwestern", centroidX: 547.81, centroidY: 247.32 },
  { id: "comarca-alt-emporda", slug: "alt-emporda", dialectGroup: "ca-central", macroDialect: "central", centroidX: 761.9, centroidY: 238.27 },
  { id: "comarca-garrotxa", slug: "garrotxa", dialectGroup: "ca-central", macroDialect: "central", centroidX: 709.48, centroidY: 258.13 },
  { id: "comarca-pallars-jussa", slug: "pallars-jussa", dialectGroup: "ca-nwestern", macroDialect: "northwestern", centroidX: 479.86, centroidY: 240.82 },
  { id: "comarca-solsones", slug: "solsones", dialectGroup: "ca-nwestern", macroDialect: "northwestern", centroidX: 561.4, centroidY: 296.85 },
  { id: "comarca-bergueda", slug: "bergueda", dialectGroup: "ca-nwestern", macroDialect: "northwestern", centroidX: 609.17, centroidY: 271.62 },
  { id: "comarca-pla-de-estany", slug: "pla-de-estany", dialectGroup: "ca-central", macroDialect: "central", centroidX: 739.77, centroidY: 266.91 },
  { id: "comarca-noguera", slug: "noguera", dialectGroup: "ca-nwestern", macroDialect: "northwestern", centroidX: 481.9, centroidY: 317.56 },
  { id: "comarca-osona", slug: "osona", dialectGroup: "ca-central", macroDialect: "central", centroidX: 666.56, centroidY: 300.83 },
  { id: "comarca-la-selva", slug: "la-selva", dialectGroup: "ca-central", macroDialect: "central", centroidX: 729.56, centroidY: 317.9 },
  { id: "comarca-baix-emporda", slug: "baix-emporda", dialectGroup: "ca-central", macroDialect: "central", centroidX: 781.46, centroidY: 299.34 },
  { id: "comarca-girones", slug: "girones", dialectGroup: "ca-central", macroDialect: "central", centroidX: 746.23, centroidY: 301.95 },
  { id: "comarca-segarra", slug: "segarra", dialectGroup: "ca-central", macroDialect: "central", centroidX: 538.05, centroidY: 342.13 },
  { id: "comarca-valles-oriental", slug: "valles-oriental", dialectGroup: "ca-central", macroDialect: "central", centroidX: 676.96, centroidY: 357.77 },
  { id: "comarca-segria", slug: "segria", dialectGroup: "ca-nwestern", macroDialect: "northwestern", centroidX: 428.24, centroidY: 375.77 },
  { id: "comarca-bages", slug: "bages", dialectGroup: "ca-central", macroDialect: "central", centroidX: 612.51, centroidY: 334.11 },
  { id: "comarca-urgell", slug: "urgell", dialectGroup: "ca-nwestern", macroDialect: "northwestern", centroidX: 496.66, centroidY: 357.31 },
  { id: "comarca-valles-occidental", slug: "valles-occidental", dialectGroup: "ca-central", macroDialect: "central", centroidX: 639.01, centroidY: 374.13 },
  { id: "comarca-anoia", slug: "anoia", dialectGroup: "ca-central", macroDialect: "central", centroidX: 576.64, centroidY: 365.36 },
  { id: "comarca-alt-penedes", slug: "alt-penedes", dialectGroup: "ca-central", macroDialect: "central", centroidX: 588.61, centroidY: 412.09 },
  { id: "comarca-alt-camp", slug: "alt-camp", dialectGroup: "ca-central", macroDialect: "central", centroidX: 532.16, centroidY: 418.39 },
  { id: "comarca-baix-penedes", slug: "baix-penedes", dialectGroup: "ca-central", macroDialect: "central", centroidX: 565.2, centroidY: 429.21 },
  { id: "comarca-baix-camp", slug: "baix-camp", dialectGroup: "ca-central", macroDialect: "central", centroidX: 488.26, centroidY: 455.21 },
  { id: "comarca-ripolles", slug: "ripolles", dialectGroup: "ca-central", macroDialect: "central", centroidX: 656.54, centroidY: 247.69 },
  { id: "comarca-pla-urgell", slug: "pla-urgell", dialectGroup: "ca-nwestern", macroDialect: "northwestern", centroidX: 476.55, centroidY: 360.38 },
  { id: "comarca-maresme", slug: "maresme", dialectGroup: "ca-central", macroDialect: "central", centroidX: 704.75, centroidY: 371.55 },
  { id: "comarca-baix-llobregat", slug: "baix-llobregat", dialectGroup: "ca-central", macroDialect: "central", centroidX: 629.37, centroidY: 399.19 },
  { id: "comarca-garrigues", slug: "garrigues", dialectGroup: "ca-nwestern", macroDialect: "northwestern", centroidX: 465.86, centroidY: 399.15 },
  { id: "comarca-conca-de-barbera", slug: "conca-de-barbera", dialectGroup: "ca-central", macroDialect: "central", centroidX: 517.66, centroidY: 398.77 },
  { id: "comarca-barcelones", slug: "barcelones", dialectGroup: "ca-central", macroDialect: "central", centroidX: 655.35, centroidY: 405.11 },
  { id: "comarca-priorat", slug: "priorat", dialectGroup: "ca-central", macroDialect: "central", centroidX: 464.74, centroidY: 442.16 },
  { id: "comarca-rebera-ebre", slug: "rebera-ebre", dialectGroup: "ca-nwestern", macroDialect: "northwestern", centroidX: 436.62, centroidY: 457.27 },
  { id: "comarca-garraf", slug: "garraf", dialectGroup: "ca-central", macroDialect: "central", centroidX: 604.15, centroidY: 433.55 },
  { id: "comarca-terra-alta", slug: "terra-alta", dialectGroup: "ca-nwestern", macroDialect: "northwestern", centroidX: 402.84, centroidY: 477.2 },
  { id: "comarca-tarragones", slug: "tarragones", dialectGroup: "ca-central", macroDialect: "central", centroidX: 533.08, centroidY: 452.88 },
  { id: "comarca-baix-ebre", slug: "baix-ebre", dialectGroup: "ca-nwestern", macroDialect: "northwestern", centroidX: 427.01, centroidY: 510.51 },
  { id: "comarca-montsia", slug: "montsia", dialectGroup: "ca-nwestern", macroDialect: "northwestern", centroidX: 422.65, centroidY: 547.69 },
  { id: "comarca-catalunya-nord", slug: "catalunya-nord", dialectGroup: "ca-northern", macroDialect: "northern", centroidX: 694.26, centroidY: 172.83 },
  { id: "comarca-catalunya-nord-2", slug: "catalunya-nord-2", dialectGroup: "ca-northern", macroDialect: "northern", centroidX: 706.08, centroidY: 142.48 },
  { id: "comarca-mallorca", slug: "mallorca", dialectGroup: "ca-balear", macroDialect: "balearic", centroidX: 589.41, centroidY: 643.65 },
  { id: "comarca-menorca", slug: "menorca", dialectGroup: "ca-balear", macroDialect: "balearic", centroidX: 752.02, centroidY: 580.12 },
  { id: "comarca-eivissa", slug: "eivissa", dialectGroup: "ca-balear", macroDialect: "balearic", centroidX: 378.43, centroidY: 756.98 },
  { id: "comarca-cabrera", slug: "cabrera", dialectGroup: "ca-balear", macroDialect: "balearic", centroidX: 594.83, centroidY: 726.86 },
  { id: "comarca-formentera", slug: "formentera", dialectGroup: "ca-balear", macroDialect: "balearic", centroidX: 388.03, centroidY: 808.95 },
  { id: "comarca-valencia", slug: "valencia", dialectGroup: "ca-valencia", macroDialect: "valencian", centroidX: 277.13, centroidY: 793.51 },
  { id: "comarca-andorra", slug: "andorra", dialectGroup: "ca-nwestern", macroDialect: "northwestern", centroidX: 574.15, centroidY: 188.59 },
  { id: "comarca-ardemuz", slug: "ardemuz", dialectGroup: "ca-nwestern", macroDialect: "northwestern", centroidX: 168.19, centroidY: 650.49 },
];

