// Generated by scripts/refactor_catalan_map.py — centroids refreshed by snap_oracle_communities.py.
import type { DialectZone } from "./accentOracleClient";

export interface ComarcaMapEntry {
  id: string;
  slug: string;
  dialectGroup: string;
  macroDialect: DialectZone;
  centroidX: number;
  centroidY: number;
}

export const COMARCA_MAP_META: ComarcaMapEntry[] = [
  { id: "comarca-vielha", slug: "vielha", dialectGroup: "ca-nwestern", macroDialect: "northwestern", centroidX: 466.69, centroidY: 157.23 },
  { id: "comarca-pallars-sobira", slug: "pallars-sobira", dialectGroup: "ca-nwestern", macroDialect: "northwestern", centroidX: 511.73, centroidY: 193.23 },
  { id: "comarca-alta-ribagorca", slug: "alta-ribagorca", dialectGroup: "ca-nwestern", macroDialect: "northwestern", centroidX: 465.23, centroidY: 205.95 },
  { id: "comarca-cerdanya", slug: "cerdanya", dialectGroup: "ca-nwestern", macroDialect: "northwestern", centroidX: 605.87, centroidY: 217.83 },
  { id: "comarca-alt-urgell", slug: "alt-urgell", dialectGroup: "ca-nwestern", macroDialect: "northwestern", centroidX: 540.23, centroidY: 250.64 },
  { id: "comarca-alt-emporda", slug: "alt-emporda", dialectGroup: "ca-central", macroDialect: "central", centroidX: 778.96, centroidY: 235.50 },
  { id: "comarca-garrotxa", slug: "garrotxa", dialectGroup: "ca-central", macroDialect: "central", centroidX: 708.33, centroidY: 257.36 },
  { id: "comarca-pallars-jussa", slug: "pallars-jussa", dialectGroup: "ca-nwestern", macroDialect: "northwestern", centroidX: 480.23, centroidY: 241.52 },
  { id: "comarca-solsones", slug: "solsones", dialectGroup: "ca-nwestern", macroDialect: "northwestern", centroidX: 567.78, centroidY: 295.15 },
  { id: "comarca-bergueda", slug: "bergueda", dialectGroup: "ca-nwestern", macroDialect: "northwestern", centroidX: 607.98, centroidY: 272.36 },
  { id: "comarca-pla-de-estany", slug: "pla-de-estany", dialectGroup: "ca-central", macroDialect: "central", centroidX: 743.21, centroidY: 265.70 },
  { id: "comarca-noguera", slug: "noguera", dialectGroup: "ca-nwestern", macroDialect: "northwestern", centroidX: 486.13, centroidY: 313.87 },
  { id: "comarca-osona", slug: "osona", dialectGroup: "ca-central", macroDialect: "central", centroidX: 668.36, centroidY: 296.43 },
  { id: "comarca-la-selva", slug: "la-selva", dialectGroup: "ca-central", macroDialect: "central", centroidX: 728.50, centroidY: 321.35 },
  { id: "comarca-baix-emporda", slug: "baix-emporda", dialectGroup: "ca-central", macroDialect: "central", centroidX: 787.10, centroidY: 300.42 },
  { id: "comarca-girones", slug: "girones", dialectGroup: "ca-central", macroDialect: "central", centroidX: 750.14, centroidY: 295.52 },
  { id: "comarca-segarra", slug: "segarra", dialectGroup: "ca-central", macroDialect: "central", centroidX: 537.29, centroidY: 342.52 },
  { id: "comarca-valles-oriental", slug: "valles-oriental", dialectGroup: "ca-central", macroDialect: "central", centroidX: 673.40, centroidY: 351.85 },
  { id: "comarca-segria", slug: "segria", dialectGroup: "ca-nwestern", macroDialect: "northwestern", centroidX: 427.17, centroidY: 376.67 },
  { id: "comarca-bages", slug: "bages", dialectGroup: "ca-central", macroDialect: "central", centroidX: 610.69, centroidY: 329.25 },
  { id: "comarca-urgell", slug: "urgell", dialectGroup: "ca-nwestern", macroDialect: "northwestern", centroidX: 501.35, centroidY: 352.37 },
  { id: "comarca-valles-occidental", slug: "valles-occidental", dialectGroup: "ca-central", macroDialect: "central", centroidX: 640.23, centroidY: 375.49 },
  { id: "comarca-anoia", slug: "anoia", dialectGroup: "ca-central", macroDialect: "central", centroidX: 572.08, centroidY: 365.72 },
  { id: "comarca-alt-penedes", slug: "alt-penedes", dialectGroup: "ca-central", macroDialect: "central", centroidX: 587.30, centroidY: 412.05 },
  { id: "comarca-alt-camp", slug: "alt-camp", dialectGroup: "ca-central", macroDialect: "central", centroidX: 536.13, centroidY: 421.95 },
  { id: "comarca-baix-penedes", slug: "baix-penedes", dialectGroup: "ca-central", macroDialect: "central", centroidX: 568.47, centroidY: 431.45 },
  { id: "comarca-baix-camp", slug: "baix-camp", dialectGroup: "ca-central", macroDialect: "central", centroidX: 489.68, centroidY: 458.59 },
  { id: "comarca-ripolles", slug: "ripolles", dialectGroup: "ca-central", macroDialect: "central", centroidX: 658.52, centroidY: 245.90 },
  { id: "comarca-pla-urgell", slug: "pla-urgell", dialectGroup: "ca-nwestern", macroDialect: "northwestern", centroidX: 475.52, centroidY: 361.08 },
  { id: "comarca-maresme", slug: "maresme", dialectGroup: "ca-central", macroDialect: "central", centroidX: 700.32, centroidY: 371.89 },
  { id: "comarca-baix-llobregat", slug: "baix-llobregat", dialectGroup: "ca-central", macroDialect: "central", centroidX: 628.57, centroidY: 402.51 },
  { id: "comarca-garrigues", slug: "garrigues", dialectGroup: "ca-nwestern", macroDialect: "northwestern", centroidX: 466.96, centroidY: 398.87 },
  { id: "comarca-conca-de-barbera", slug: "conca-de-barbera", dialectGroup: "ca-central", macroDialect: "central", centroidX: 518.97, centroidY: 398.54 },
  { id: "comarca-barcelones", slug: "barcelones", dialectGroup: "ca-central", macroDialect: "central", centroidX: 657.22, centroidY: 406.48 },
  { id: "comarca-priorat", slug: "priorat", dialectGroup: "ca-central", macroDialect: "central", centroidX: 463.43, centroidY: 443.98 },
  { id: "comarca-rebera-ebre", slug: "rebera-ebre", dialectGroup: "ca-nwestern", macroDialect: "northwestern", centroidX: 439.65, centroidY: 457.56 },
  { id: "comarca-garraf", slug: "garraf", dialectGroup: "ca-central", macroDialect: "central", centroidX: 603.80, centroidY: 434.60 },
  { id: "comarca-terra-alta", slug: "terra-alta", dialectGroup: "ca-nwestern", macroDialect: "northwestern", centroidX: 395.80, centroidY: 473.40 },
  { id: "comarca-tarragones", slug: "tarragones", dialectGroup: "ca-central", macroDialect: "central", centroidX: 526.87, centroidY: 454.22 },
  { id: "comarca-baix-ebre", slug: "baix-ebre", dialectGroup: "ca-nwestern", macroDialect: "northwestern", centroidX: 439.27, centroidY: 512.32 },
  { id: "comarca-montsia", slug: "montsia", dialectGroup: "ca-nwestern", macroDialect: "northwestern", centroidX: 418.90, centroidY: 547.60 },
  { id: "comarca-catalunya-nord", slug: "catalunya-nord", dialectGroup: "ca-northern", macroDialect: "northern", centroidX: 701.71, centroidY: 187.08 },
  { id: "comarca-catalunya-nord-2", slug: "catalunya-nord-2", dialectGroup: "ca-northern", macroDialect: "northern", centroidX: 704.99, centroidY: 140.21 },
  { id: "comarca-mallorca", slug: "mallorca", dialectGroup: "ca-balear", macroDialect: "balearic", centroidX: 762.73, centroidY: 742.51 },
  { id: "comarca-menorca", slug: "menorca", dialectGroup: "ca-balear", macroDialect: "balearic", centroidX: 929.97, centroidY: 679.84 },
  { id: "comarca-eivissa", slug: "eivissa", dialectGroup: "ca-balear", macroDialect: "balearic", centroidX: 547.88, centroidY: 856.01 },
  { id: "comarca-cabrera", slug: "cabrera", dialectGroup: "ca-balear", macroDialect: "balearic", centroidX: 764.90, centroidY: 826.85 },
  { id: "comarca-formentera", slug: "formentera", dialectGroup: "ca-balear", macroDialect: "balearic", centroidX: 555.09, centroidY: 908.52 },
  { id: "comarca-valencia", slug: "valencia", dialectGroup: "ca-valencia", macroDialect: "valencian", centroidX: 272.15, centroidY: 754.73 },
  { id: "comarca-andorra", slug: "andorra", dialectGroup: "ca-nwestern", macroDialect: "northwestern", centroidX: 572.80, centroidY: 187.26 },
  { id: "comarca-ardemuz", slug: "ardemuz", dialectGroup: "ca-nwestern", macroDialect: "northwestern", centroidX: 163.72, centroidY: 653.57 },
];

