// Generated by scripts/build_read_aloud_prompts.py; do not hand-edit.

export type GeneratedReadAloudPrompt = {
  id: string;
  text: string;
  sentenceIds: readonly string[];
};

export const GENERATED_READ_ALOUD_PROMPTS: readonly GeneratedReadAloudPrompt[] = 
[
  {
    "id": "cv26-c42a51c02f46cdfd",
    "text": "No hi haurà cap limitació tècnica a implementar qualsevol bandera de les comunitats autònomes de l'estat espanyol.",
    "sentenceIds": [
      "458f47bda1991313c9c7da89b21070919d4684e60dfe5fe0c5415b7af63b734b"
    ]
  },
  {
    "id": "cv26-a4aa19d9d83d64c0",
    "text": "El resultat és força conegut: l'abstracció musical del motiu com a símbol específic, carregat de significació.",
    "sentenceIds": [
      "4cbff4e87cb95ad176bfb85300954d46ace16a08cc1d079aa6fb5a933d80ff62"
    ]
  },
  {
    "id": "cv26-4671eff039bc79b2",
    "text": "Xavier Carbó i Maymí va ser un clergue, poeta, lingüista i traductor dels clàssics nascut a Cassà de la Selva.",
    "sentenceIds": [
      "ea6509d1d64ac5ae69a0862cfa7c80338130fb312a8be0de831e67c75f474797"
    ]
  },
  {
    "id": "cv26-208827518a4219fa",
    "text": "Per evitar això, els estats fan una excepció al desitjable principi de lliure competència i concedeixen patents.",
    "sentenceIds": [
      "38fa744ceb6d1abac21268ed800663b731796b9a303bde420fda2c6cb63c4411"
    ]
  },
  {
    "id": "cv26-a4e5cf5cf81a5d54",
    "text": "Tan aviat com intentava gitar-se s'ofegava, i calia córrer a alçar-ho, com si li haguera arribat la darrera hora.",
    "sentenceIds": [
      "423bb32d94d3c4e0fdbb63ec51d750371478502e64fefc9dd557b65631f125ab"
    ]
  },
  {
    "id": "cv26-84deb10d1e605215",
    "text": "Però deixarem de banda aquests càlculs matemàtics i ens centrarem a esbrinar la relació entre competència i ús.",
    "sentenceIds": [
      "f63d0b722866b7a1707ad967bff0438663256ef72cf4841629b6116b64ebdde7"
    ]
  },
  {
    "id": "cv26-1f749504e89e328f",
    "text": "D'aquesta manera s'obté reconeixement del capital intel·lectual del participant, cosa que es pot traduir en oportunitats laborals.",
    "sentenceIds": [
      "66cd2dc79040067f561efa38c95d66ea51716e40156aa676a37c6d13af41c78a"
    ]
  },
  {
    "id": "cv26-887f49c5f857c25f",
    "text": "Sunifred primer d'Urgell-Cerdanya va ser un comte d'Urgell, Cerdanya, Barcelona, Girona entre d'altres nascut a Girona.",
    "sentenceIds": [
      "58548ef9fc0be0b12f2e2aa22f5fdf603786b46026ecdd92387d0deeecaa1992"
    ]
  },
  {
    "id": "cv26-5d71510e5500bedb",
    "text": "Quina és la millor manera d'anar de la carretera de Santa Creu d'Olorda a Sarrià al carrer de l'Arc del Teatre?",
    "sentenceIds": [
      "52009a79da66ca47f052b8923f7bfcb41a30c7be9d5440f69b7df361b536ff73"
    ]
  },
  {
    "id": "cv26-ad37a9827ae365ea",
    "text": "Al llarg del dos mil quinze s'han baixat quatre-centes vint-i-nou cent vuitanta-tres còpies de programes en català des del nostre lloc web.",
    "sentenceIds": [
      "260009e9face720c1fbfb98cea6b26f403ea8f5ca0de3e9652dab375ea487a51"
    ]
  },
  {
    "id": "cv26-4e0168f3f71de10f",
    "text": "I en dir açò, assenyalava a un pillet enviat, immòbil a curta distància, amb un capó gros i llustrós als braços.",
    "sentenceIds": [
      "d780237ec92e11fbaea67ad8b10195fe41be9e28d8d86c10c3383c7abf91c999"
    ]
  },
  {
    "id": "cv26-1ad7b034870a48a8",
    "text": "Feliu Elias i Bracons va ser un dibuixant, caricaturista, pintor, il·lustrador i crític d'art nascut a Barcelona.",
    "sentenceIds": [
      "9d1a6e4c191b00292357f7927a8f716808891af734a6fef119e66745c0328b64"
    ]
  },
  {
    "id": "cv26-61234159f5850112",
    "text": "Regne Unit, amb nou milions tres-cents trenta-tres mil vuit-cents noranta-un casos i cent quaranta-un mil vuit-cents seixanta-dos morts.",
    "sentenceIds": [
      "78239e78c23bf4b8f35e672bb566adbf6e80ba8ffa29e44e644029eebcdb52c5"
    ]
  },
  {
    "id": "cv26-01b6d2a5153c8b9d",
    "text": "Se sentia feliç i plorava d'alegria, d'agraïment, satisfeta d'ella mateixa, de la bondat amb què la tractava Déu.",
    "sentenceIds": [
      "47fff7e828ecbbf151ec8d4a0e811ad31db9613cb9e4d5174e75cd3639d3abe2"
    ]
  },
  {
    "id": "cv26-d9a5a987f84d704e",
    "text": "Josep Rosell i Casablancas va ser un esportista, excursionista, periodista, historiador i cronista nascut a Sabadell.",
    "sentenceIds": [
      "36c95798e8d176a9e6fd76c505b06197ab469f1a3c979206db85272ae8e9261a"
    ]
  },
  {
    "id": "cv26-409bf18c8da8379e",
    "text": "Rússia, amb vuit milions nou-cents noranta-dos mil cinc-cents noranta-cinc casos i dos-cents cinquanta-dos mil nou-cents vint-i-sis morts.",
    "sentenceIds": [
      "3a9a91cb09dc482e97903ef60b691b3faeff32983dce7bfa61ac0b410ac719ad"
    ]
  },
  {
    "id": "cv26-44be9566e8573e15",
    "text": "Josep Blanch i Graells va ser un compositor i abat del monestir de Montserrat nascut a Vilafranca del Penedès.",
    "sentenceIds": [
      "91e9aebd37a95de0c990216400c22cdb0a5317e28b371a139e60a28bed7ee9e8"
    ]
  },
  {
    "id": "cv26-2523df20e91a3a2f",
    "text": "Jaume Almirall i Sardà és un hel·lenista, neohel·lenista, professor i traductor nascut a Sant Sadurní d'Anoia.",
    "sentenceIds": [
      "db44d87f3dbab3404378d1603e49ea79aa95adc713661b08fdb5ac0c9121db5f"
    ]
  },
  {
    "id": "cv26-ebe8a6f915f9f8f5",
    "text": "A més a més, en general, les obres de construcció d'un edifici d'habitatges normal pot durar entre un i dos anys.",
    "sentenceIds": [
      "1d3fc7bf88bcfdb5075b03f800f3577cf99a6ab460ae8257aa2b415d30011592"
    ]
  },
  {
    "id": "cv26-b9e2d04b814bd393",
    "text": "Fins a quinze punts: mèrits científico-tècnics de la persona que avala la sol·licitud en el centre de destinació.",
    "sentenceIds": [
      "c210fb87565aeb3653c78a9cdbe1ed5a3950d860a626c39398f43837e5644895"
    ]
  },
  {
    "id": "cv26-17cf41a8748d15f1",
    "text": "I el numero de targeta és quatre mil cinc-cents setanta-tres quatre mil cinc-cents seixanta-dos cinc mil sis-cents quaranta-tres nou mil cent setanta-tres.",
    "sentenceIds": [
      "e9d2f9984122f709c24d138c5dbcfe5c10faee1e44f4cead127b71f381c070dc"
    ]
  },
  {
    "id": "cv26-57ee4e2891408297",
    "text": "La liberalització de les telecomunicacions d'aquest moment no té res a veure amb els pronòstics que la van animar.",
    "sentenceIds": [
      "2461e8e2e9830b498ae0aca4c3b29dfb47040f4c6233c5859f7f7badf34381a7"
    ]
  },
  {
    "id": "cv26-195a488fcfcdf51b",
    "text": "No es podrà transmetre cànnabis o altres substàncies tòxiques a persones que no siguin sòcies del Club social.",
    "sentenceIds": [
      "34fb9449446774a6adce9c89ad536d39ac25b96e322f3e3a7fc41e816e47aab7"
    ]
  },
  {
    "id": "cv26-91d852a448a6f241",
    "text": "Per a l'usuari final, després del sistema operatiu, el paquet ofimàtic és el conjunt de programes més utilitzats.",
    "sentenceIds": [
      "d16e7e03a51ffd768801a0eec4a277d20e98772ae7a165eb99e036abd71d8ed1"
    ]
  },
  {
    "id": "cv26-baf15db6072fbec1",
    "text": "Reserva'm un bitllet de tren per anar a Torrelles de Llobregat el vint-i-tres de maig a dos quarts i cinc de set.",
    "sentenceIds": [
      "91def838b174a074cd8d99953d613024b9adcde48cd648c68ac7cc9f39f1d013"
    ]
  },
  {
    "id": "cv26-a423b600889e4887",
    "text": "L'altre, sota la figura del vidrier, ens mostra el productor la indústria del qual és fomentada per l'accident.",
    "sentenceIds": [
      "0690c697cc117457f26def3bbe47b504ce21754910e2972d4e694dbfc1f2b1ed"
    ]
  },
  {
    "id": "cv26-297982c1adba12b3",
    "text": "Hi ha una correlació directa entre el nombre d'usuaris que té una aplicació lliure i la comunitat que li dóna suport.",
    "sentenceIds": [
      "232f9006a985db802ac46d23700249ebd560d6b47a7776cda725027a7109a2d2"
    ]
  },
  {
    "id": "cv26-45bf370b99456c5c",
    "text": "En el cas d'accions formatives realitzades en el marc de la Via tres, els alumnes només podran ser desocupats.",
    "sentenceIds": [
      "292c064918b6c872fd12a496123fe2efdd7f6e87dadcd5663b92a68acd24bd8b"
    ]
  },
  {
    "id": "cv26-27594f5db50878bd",
    "text": "Són membres nats el rector o rectora, el secretari o secretària general i el gerent o la gerent de la Universitat.",
    "sentenceIds": [
      "1e96c71cbf2251a4a1c26049763ad9816196375f15c8be835c70c00393bdc7c6"
    ]
  },
  {
    "id": "cv26-40ffa9bc69acf7c8",
    "text": "Els drets d'autor són l'eina jurídica bàsica utilitzada per a la protecció dels programes informàtics i les creacions intel·lectuals.",
    "sentenceIds": [
      "0ba8bc51ec2dfd82a4f37b602f3265f788b2a022eb9aa9ded5d086a1fb6834c2"
    ]
  },
  {
    "id": "cv26-9e8acd3fd141af0f",
    "text": "Quan s'ha considerat necessari, es completa la informació amb notes de tipus conceptual, lingüístic o pragmàtic.",
    "sentenceIds": [
      "ca4502812151f86e53cdf9a1ccef17c4865144aaf55487bf504da171becd357d"
    ]
  },
  {
    "id": "cv26-113d10170c9da45a",
    "text": "Les tres comunitats amb una concentració més alta d'empreses de programari lliure eren Madrid, amb seixanta-vuit, Catalunya, amb quaranta-sis, i Andalusia, amb quaranta.",
    "sentenceIds": [
      "76c135686e96efcc3f7e762a12194db1bb6e6bcd516cc9ba4ffed5a7122d1881"
    ]
  },
  {
    "id": "cv26-f78f1567b7506744",
    "text": "Mira'm quina és la millor manera d'anar del passatge d'Isabel Vicente al carrer de la Mare de Déu de la Salut.",
    "sentenceIds": [
      "7d9f977a6ceac7804c272cd90459c120c9cf02d5f06a30d5a47ca73f1de6f474"
    ]
  },
  {
    "id": "cv26-bd0241c1a7c3961b",
    "text": "Després de vint-i-cinc anys, el planejament en l'entorn del Mercat de Mossén Sorell està completament embossat.",
    "sentenceIds": [
      "50b183cea43bfe583cb245471740229150c52e7e769d1abfafccf634d6b6dbf1"
    ]
  },
  {
    "id": "cv26-be7b20bbf49ff364",
    "text": "Hi ha qui creu, erròniament, que la venda de llicències és una font extraordinària d'ingressos per a qualsevol empresa.",
    "sentenceIds": [
      "5a5d17e8d4ebd41fb37d1fbb1fe1a95c6c3ace2a65841efb5067cedcd7d29ba5"
    ]
  },
  {
    "id": "cv26-95abd2c9cf52f9b5",
    "text": "Qualsevol empresa o professional, amb els coneixements adequats, pot seguir oferint desenvolupament o serveis per a la nostra aplicació.",
    "sentenceIds": [
      "380aa64b806b56cb4fa9b23ff961fa57915ece6edb099f9787957a468cfd6791"
    ]
  },
  {
    "id": "cv26-a23a9a17e627975d",
    "text": "El quinze de gener de dos mil u nasqué la Viquipèdia i el setze de març del mateix any ho féu la Viquipèdia en català.",
    "sentenceIds": [
      "055ca0d9ed8d89cb452fd36ff6522cd0c1d3d268d454d12d00d6496b2f36664f"
    ]
  },
  {
    "id": "cv26-3f771d5cb995b9e5",
    "text": "L'empresa va gastar aproximadament tretze milions de dòlars i va arribar a tenir setanta empleats en plantilla.",
    "sentenceIds": [
      "427176c4242e6de6e8b5d2a7c7e37f27736f93dcaf916aa096fdbf55bac4bc42"
    ]
  },
  {
    "id": "cv26-93d4a1dd861fb833",
    "text": "Això vol dir que el consorci ha desacoblat l'actualització dels emojis de l'actualització de l'estàndard Unicode.",
    "sentenceIds": [
      "e5151b7ddf56994ad458de0113147880b2dbe827d25531152aad5a1500dfd198"
    ]
  },
  {
    "id": "cv26-10d7df5a9c47b447",
    "text": "Esquerra Republicana de Catalunya parla d'eixamplar la base social de l'independentisme, incorporant polítics d'altres opcions polítiques properes.",
    "sentenceIds": [
      "ea4a88a5f6029490c8506ec66b95406f15b709c96b999dd92e9671cb9777afa8"
    ]
  },
  {
    "id": "cv26-8f01d049b84f42dd",
    "text": "Per l'abril, blat espigat; pel maig, granat; pel juny, segat; pel juliol, trillat; per l'agost, mòlt i pastat.",
    "sentenceIds": [
      "08ea3e76ee44d56c834b2034c1f8ba84e87e68e7726d4616ae9bc01ac586b87e"
    ]
  },
  {
    "id": "cv26-621cfcdef4dc2904",
    "text": "Per això, utilitzen unes circumscripcions de no més de cinc escons a la República d'Irlanda i de sis a l'Ulster.",
    "sentenceIds": [
      "ed9a4310accf9fe30f7bba7328cf862eaf1ad015e94661d2dd34326e5fd72938"
    ]
  },
  {
    "id": "cv26-83ff1983da7ac7b1",
    "text": "Des de la seva creació, la fundació ha rebut més de cinc-centes contribucions econòmiques d'empreses i particulars.",
    "sentenceIds": [
      "7648be225fe47d97ce3108bb6696f6b5f5c9094d792a43d39040bbf146fa15c4"
    ]
  },
  {
    "id": "cv26-a9700daa1dccb849",
    "text": "Mentre que Bruce Byfield de Linux Pro Magazine Online escrivia Calligra necessitava un primer llançament impressionant.",
    "sentenceIds": [
      "6117ef6bfdb0c8cb1789ed8bba07e1ef722be774faf52b991f59da4cffdd556c"
    ]
  },
  {
    "id": "cv26-ff2ff95a9f9a657b",
    "text": "De fet, en aquest context tan hostil resulta quasi un «miracle» que el valencià —amb penúries, sí— sobrevisca.",
    "sentenceIds": [
      "bb89e577ee99e1e3531795d8a55b50cc973789b27bdf6c09983e14a6e9d04916"
    ]
  },
  {
    "id": "cv26-58cf4ad820eb397a",
    "text": "Regne Unit, amb vuit milions vuitanta-un mil tres-cents casos i cent trenta-set mil cinc-cents quaranta-un morts.",
    "sentenceIds": [
      "37526903430c64e397cf820782c127275edd3b7e35fb9c96d7e2b129cc681a25"
    ]
  },
  {
    "id": "cv26-8235a77331f853bb",
    "text": "Hi ha diverses llicències legals que garanteixen això, amb garanties per a l'autor i el conjunt de la societat.",
    "sentenceIds": [
      "3dfe84f73707d52ada1445633461f79febbeac06d54f8de53f3af8965d6ef364"
    ]
  },
  {
    "id": "cv26-af1d8ab11a32f976",
    "text": "Però en països on no és ni jutge ni general, com a Anglaterra, a males penes es podria saber quin és el seu ofici.",
    "sentenceIds": [
      "e3cb122b562cb348656633fe7a95704b7c44f2b39092ad33e54b1eb06cbc9caa"
    ]
  },
  {
    "id": "cv26-8c48e534354c67ad",
    "text": "Una segona característica, que també suposa un gran repte, és la necessitat d'augmentar de l'esforç innovador.",
    "sentenceIds": [
      "63f9d29689801559cb4dc1785636f42dfd219820a193ef8fb5d37df41291258d"
    ]
  },
  {
    "id": "cv26-fddfe74d98df709a",
    "text": "Si en algun punt té alguna llacuna de coneixement, només cal que no n'escrigui res: algú altre ja ho completarà.",
    "sentenceIds": [
      "7ca5054553c348a18bf2749699dc8d178c3a237d5ae6e53a40dd158e83e1487b"
    ]
  },
  {
    "id": "cv26-a9488b6e6e283d3b",
    "text": "Regne Unit, amb setze milions quatre-cents seixanta-vuit mil cinc-cents vint-i-dos casos i cent cinquanta-cinc mil sis-cents noranta-vuit morts.",
    "sentenceIds": [
      "9faa6b7876929ec30a9051cd1fd4fff388cb1ed1aefeaa7eba846f00b02c393f"
    ]
  },
  {
    "id": "cv26-df024d00ad9a6794",
    "text": "A tot el món, les darreres xifres són de cinquanta-cinc milions setanta-nou mil cent nou confirmats i un milió tres-cents vint-i-vuit mil dos-cents seixanta-dos morts.",
    "sentenceIds": [
      "d81f5cb1d9e7ae58a86c797200741f07c5cd2c3979a0fa64cf60731ab878bc49"
    ]
  },
  {
    "id": "cv26-be9a807eccba54ed",
    "text": "Tot i que la mostra no és una botiga, si algun grup té material representatiu vendible, també el podria portar.",
    "sentenceIds": [
      "cc544babd4e9c0c1fcf1bccfa00ac5d777ffacaee67b87566e59e636eea5a336"
    ]
  },
  {
    "id": "cv26-20b205f79291a93c",
    "text": "Quina és la millor manera d'anar del carrer de la Capella de Can Caralleu al carrer del Doctor Farreras i Valentí?",
    "sentenceIds": [
      "52a3fefef9a79c2de3789b615cdbb726d2c81a7a1b892600e0ec2b6ec8b6ef9e"
    ]
  },
  {
    "id": "cv26-cfc205a055e88344",
    "text": "Aquesta versió, com les anteriors, no descuida el rendiment, i s'han fet millores importants en aquest aspecte.",
    "sentenceIds": [
      "738d882bbc8989290d5e0fca17d8877cea109d321b2702bd34f5000c4ba980bb"
    ]
  },
  {
    "id": "cv26-e814a58708d08fc2",
    "text": "Els tres principals sectors industrials de Fremont són el processament d'aliments, la fabricació de metall i els teleserveis.",
    "sentenceIds": [
      "bbce2da47a2b4ee8174441120c79cb3715b6fdd9e0e76a514e6304002318faba"
    ]
  },
  {
    "id": "cv26-482d7dcb01a6ae4d",
    "text": "En total hi ha més de vuitanta mil nou-cents seixanta-set contagiats i tres mil dos-cents quaranta-vuit morts.",
    "sentenceIds": [
      "3d81cf77500a9694a57a07745c0b593e042aedc094713622197c52480378fbcc"
    ]
  },
  {
    "id": "cv26-b01c3200167a9f56",
    "text": "Afegeix a l'agenda el número de la Fiona Carrasquilla: set, quaranta-set, zero, set, vint-i-cinc, zero, quatre.",
    "sentenceIds": [
      "e24c704421e4a1391a5549c2fea6e60cbe6cf2e270888d2a3c3b76f6ea91c4d5"
    ]
  },
  {
    "id": "cv26-fbcb6da9cc554bf3",
    "text": "L'engany és un gran senyal de covardia, perquè l'altre actua confiadament i no utilitza mitjans d'autodefensa.",
    "sentenceIds": [
      "2d44257c105efb72eb4b1f07b79d1b48125c1814fd1bbc1352500ca7c8a37ee5"
    ]
  },
  {
    "id": "cv26-1c0bd9687bec06d1",
    "text": "Els articles podran dividir-se en apartats en el cas que regulen aspectes que s'hagen de diferenciar amb precisió.",
    "sentenceIds": [
      "68f88c134b1d7c1fa529cb27c31b4c0fd752a7d043e9c9d5a0f91357d3ed2e91"
    ]
  },
  {
    "id": "cv26-10dd5b44b8af21ce",
    "text": "Els fills, quan són petits són de les mares, quan són fadrins són de les noies i quan són casats són de la dona.",
    "sentenceIds": [
      "24496e548c87bbe44632aad89850c970efab525a3c6ef12c5439ea5298157fda"
    ]
  },
  {
    "id": "cv26-ef439bd733c235e6",
    "text": "Ignasi de Sagarra i de Castellarnau va ser un entomòleg, ornitòleg i conservador de zoologia nascut a Barcelona.",
    "sentenceIds": [
      "1097a308660b5e5699bef65b79aae88b841b9d96292a5707c814e1b0d1e367b3"
    ]
  },
  {
    "id": "cv26-dca090fa96591ee8",
    "text": "El Brasil, amb un milió quatre-cents vint-i-sis mil nou-cents tretze casos i seixanta mil cent noranta-quatre morts.",
    "sentenceIds": [
      "ef7bc1509612bc86ee2fb6f82aa42a669fa881819cdf304a6c308e958ba91949"
    ]
  },
  {
    "id": "cv26-5ee39921d0791142",
    "text": "Josep Maria Guilera Albiñana va ser un alpinista, esquiador, dirigent esportiu i assagista nascut a Barcelona.",
    "sentenceIds": [
      "a3bc951d7a6deb66640a784869569b41c01a3f630b0a4461cbfe0c157fe403f0"
    ]
  },
  {
    "id": "cv26-c9af1a8d6cf073e5",
    "text": "Rússia, amb set milions cinc-cents onze mil vint-i-sis casos i dos-cents set mil dos-cents cinquanta-cinc morts.",
    "sentenceIds": [
      "13a513011e096bb1dbc4a2b756d6b5d2345ff671e69284ccb14e3aeca5072d98"
    ]
  },
  {
    "id": "cv26-9a1d5a0177902a00",
    "text": "Mira'm quina és la millor manera d'anar de l'avinguda de la Reina Maria Cristina a la plaça de Josep M. Folch i Torres.",
    "sentenceIds": [
      "4f1fb2b4f3a4038d67c67ab1dee6fc8cf184ba4c1dac962eaa40aa7c5970177d"
    ]
  },
  {
    "id": "cv26-d7df9ebbb437abad",
    "text": "En aquest mes, la xifra de desocupats registrats ascendia a tres milions tres-cents trenta-tres mil nou-cents quinze.",
    "sentenceIds": [
      "4e254051941ad162932dc9f69944587c5d5f55f720895c0c59349ad70eb59996"
    ]
  },
  {
    "id": "cv26-d11eca22edd137cd",
    "text": "Ramona Peralba Sala va ser una teixidora, activista republicana executada pel règim franquista nascuda a Gironella.",
    "sentenceIds": [
      "ac6e1ed1dcc9a2383267f46ad03dc64fde0aceb6f6688d2d3bd4b4500afa435e"
    ]
  },
  {
    "id": "cv26-35b091f73a9c8daf",
    "text": "Rússia, amb quatre milions set-cents noranta-sis mil cinc-cents cinquanta-set casos i cent nou mil set-cents trenta-un morts.",
    "sentenceIds": [
      "080322aec9871417ad427b2f97ef67836296ea72c708ce27cfb1517e30571199"
    ]
  },
  {
    "id": "cv26-c71cdc9290a4e155",
    "text": "És una conseqüència de la instrumentalització que l'espanyolisme ha fet a casa nostra de la identitat valenciana.",
    "sentenceIds": [
      "c1501c86576bc8bc1019eca38b6acdde6a9bf9e89ef7ad395594d9802ae26a7e"
    ]
  },
  {
    "id": "cv26-b7556e7e7f250848",
    "text": "Les persones s'han reunit a la gespa per veure alguna cosa amb telescopis, possiblement amb finalitats científiques.",
    "sentenceIds": [
      "f0d03fd5317bb3b3c044664cc34b31d386d3ab772dec7289793177fa1c0e428f"
    ]
  },
  {
    "id": "cv26-77daf7b08ce8b2b9",
    "text": "Com a projecte lliure, el Catalanitzador per al Windows està obert a la col·laboració d'usuaris i programadors.",
    "sentenceIds": [
      "187ec0a97ddaff196cad7048119462ee6d7110916adf469348a91933892c94a7"
    ]
  },
  {
    "id": "cv26-1a2b7adc7cf3173c",
    "text": "Josep Oriol i Bernadet va ser un matemàtic, científic, agrimensor, poeta i arquitecte nascut al Far d'Empordà.",
    "sentenceIds": [
      "649599754294ddc79825d910b9bedeae5b88e127512436db6ff75c626cf9e769"
    ]
  },
  {
    "id": "cv26-628c2629e5218d39",
    "text": "A hores d'ara el diccionari conté cent trenta mil arrels de paraules que poden generar més d'un milió de formes.",
    "sentenceIds": [
      "10e856c567176ba0b8cfe567d8320e7276ed1745020d5a45c6953c143832bd52"
    ]
  },
  {
    "id": "cv26-3404b387bbe0ef85",
    "text": "Francisca Rius i Sanuy va ser una dibuixant, pintora, il·lustradora, professora de dibuix, escriptora nascuda a Barcelona.",
    "sentenceIds": [
      "439cab5798ed8b80e6034c319322df7d34b777e87213e6124cd899fe192cd3ba"
    ]
  },
  {
    "id": "cv26-6598aa16c58397dd",
    "text": "Rússia, amb vuit milions tres-cents cinquanta-dos mil sis-cents un casos i dos-cents trenta-tres mil vuit-cents noranta-vuit morts.",
    "sentenceIds": [
      "5ed94661c8d997333b4d96677e55a81e0719581b44c66f445d0f8c830b421e59"
    ]
  },
  {
    "id": "cv26-00e06aeec241ffa5",
    "text": "Hi ha un poble prop d'Atenes que es diu Mandra. Quan em toqui la loteria hi compraré un xalet i me n'hi aniré a viure.",
    "sentenceIds": [
      "36b9d180875506ee13a235624dcc1bd0fe01b449a058c04136865ff340a03d33"
    ]
  },
  {
    "id": "cv26-3fcad62ad57507b7",
    "text": "Maria Teresa Utgés Nogués és una metgessa especialista en psiquiatria i política nascuda a les Borges Blanques.",
    "sentenceIds": [
      "46f45bdfc95f3fd6a2d5bd0d24d88d879bd80c2a305a7f69fc89a49d2e96107f"
    ]
  },
  {
    "id": "cv26-100b7907ca6b97b9",
    "text": "Totes aquestes eines, juntament amb el talent dels membres dels diferents projectes, és el que fa possible la producció de programari lliure.",
    "sentenceIds": [
      "3d8f6a752c4cb9603e293f5e02d93b7a9c5b0338d6bf9201082cdf10d81ac0f4"
    ]
  },
  {
    "id": "cv26-b9c7cb8732559c51",
    "text": "La Universitat de Boston, ja implicada en l'educació local, va prendre el relleu de l'administració de l'escola.",
    "sentenceIds": [
      "f6df0b818c2a9c4d67d254f4918c1343f586845f52937360874ab9254966b9fa"
    ]
  },
  {
    "id": "cv26-57616fc973886c44",
    "text": "Dels fills de la meua filla, sé del cert que l'àvia en sóc; però dels fills del meu fill, potser sí i potser no.",
    "sentenceIds": [
      "8adaefd5d154531f7c2921c252721ba1dece5f6d4188be33998705c815864c01"
    ]
  },
  {
    "id": "cv26-2b0bf179f284ebf3",
    "text": "D'altra banda, en la taula dos s'arreplega la llista de clústers identificats que actualment funcionen a Catalunya.",
    "sentenceIds": [
      "0a4070e5cefa41bdab3a427e5f3989d9a4eaa9440782496aeab847d75426bacb"
    ]
  },
  {
    "id": "cv26-8ce8b0f385cbe4b0",
    "text": "La meva mare es diu Miranda De La Concepcion: de, e, espai, ela, a, espai, ce, o, ena, ce, e, pe, ce, i, o, ena.",
    "sentenceIds": [
      "0c8642a4e4f3c40d3076fa7b08ef9731923e027f81286f46a8c81a95f4fc4e6d"
    ]
  },
  {
    "id": "cv26-9553935e4e03074e",
    "text": "Mira'm quina és la millor manera d'anar del carrer dels Mestres Casals i Martorell al passeig Marítim del Bogatell.",
    "sentenceIds": [
      "8e6dc7cc95c27cadb41ede3d8970713327fab242261621a15ad0cef1087abc90"
    ]
  },
  {
    "id": "cv26-9beb8f1317715aab",
    "text": "A diferència de la majoria d'altres localitats de la seva grandària, Kawerau va ser planificat acuradament abans de construir-se.",
    "sentenceIds": [
      "3508dde7eb353b7691991aef9e3992adba3e5f970f2e835882f8122c7bddebda"
    ]
  },
  {
    "id": "cv26-bf63e9ee7812c533",
    "text": "Ricard Masó i Llunes va ser un cartògraf, aparellador, polític i activista cultural nascut a Sant Feliu de Guíxols.",
    "sentenceIds": [
      "077897513a838725151ab2bd7b2d93899758a6f05a4c661b28afaa2c00acc27e"
    ]
  },
  {
    "id": "cv26-02f534f099c9e977",
    "text": "Wolffheim es va associar amb aquesta tendència i en poc temps es va convertir en el col·laborador més pròxim de Laufenberg.",
    "sentenceIds": [
      "b9f62a4f863c06a099dc2719c3bf76487a2eb5f18cdd27badfc528a384e5ec6a"
    ]
  },
  {
    "id": "cv26-097b66cb2705fc57",
    "text": "Melòdicament, aquest interval es fa servir amb molta freqüència, i té una importància especial en les cadències.",
    "sentenceIds": [
      "ff4606aa8f6838417f24ce2b60731bad0eb30d36a2e4a347b032de7b16a708ea"
    ]
  },
  {
    "id": "cv26-349f7cd53c36ab21",
    "text": "Mira'm quina és la millor manera d'anar del carrer de la Mare de Déu del Coll als jardins de Manuel Sacristán.",
    "sentenceIds": [
      "15da33a31c70768c1fa03e08286599a7ef42ed81710004398ff5c229c2b1972b"
    ]
  },
  {
    "id": "cv26-1d70b5140d5d8d23",
    "text": "Atés al que establixen els articles quaranta-cinc i quaranta-sis de la Llei reguladora de l'activitat urbanística.",
    "sentenceIds": [
      "57f7d315ebb9af36e88de70b7fde467bbf3f595a18bfe4f59cc972f627f4ffe7"
    ]
  },
  {
    "id": "cv26-a093da4d5c178324",
    "text": "Pere Bohigas i Balaguer va ser un filòleg, bibliotecari, bibliòfil i professor nascut a Vilafranca del Penedès.",
    "sentenceIds": [
      "0468da2103ca139fbd48c1e6a9b75337de04fefca6f2b639bc4047df9a4d1628"
    ]
  },
  {
    "id": "cv26-ce80082509da1927",
    "text": "En qualsevol cas, aquests nombres situen el lloc web de Softcatalà entre els principals webs en llengua catalana.",
    "sentenceIds": [
      "aaea3e681f674b60e9bba5c64b446d21f4a39f934029ee863f83251cb952e375"
    ]
  },
  {
    "id": "cv26-80222dcf016fed02",
    "text": "Els grills i les cigales provoquen contaminació acústica i les cuques de llum, lumínica; de les vaques, ni en parlo.",
    "sentenceIds": [
      "5cef64522be8b213f204ab0549d20c18f4c5950a74a38284ed633d0f7941deb6"
    ]
  },
  {
    "id": "cv26-49473770ab4c5c96",
    "text": "En el fons, es tracta més d'una operació de màrqueting que d'una acció que busqui afegir transparència a l'explotació de les solucions Microsoft.",
    "sentenceIds": [
      "b5499e470cc435c7615738244db30072f853a408cde6043513ea1a4ee2b86008"
    ]
  },
  {
    "id": "cv26-d502aa516bc8ea0e",
    "text": "A més, va arribar a estar entre les deu cançons més populars a Dinamarca, Hongria, els Països Baixos i Suïssa.",
    "sentenceIds": [
      "ab77e8952cef30cd21d187333ba176a2589475619e3c5087a2d1d37781de8ba4"
    ]
  },
  {
    "id": "cv26-ee690dc342c2fc3c",
    "text": "Una gran part de la indústria del programari està basada en el desenvolupament de projectes on cal un programari personalitzat.",
    "sentenceIds": [
      "e257ce8015f763beb55bcb8ac0b1df44fccc62c59696d83bc0c52bc21d5f3687"
    ]
  },
  {
    "id": "cv26-e2e9bbf7c59b119a",
    "text": "A les escoles, instituts, universitats i altres centres de formació el programari cada vegada hi és més present.",
    "sentenceIds": [
      "348726e5b59efb74c9dca593f3cb76a539f607b03622990fc9fb72706caf9dee"
    ]
  },
  {
    "id": "cv26-ac705a7b88bae286",
    "text": "Rússia, amb vuit milions seixanta mil set-cents cinquanta-dos casos i dos-cents vint-i-cinc mil tres-cents vint-i-cinc morts.",
    "sentenceIds": [
      "bd4fc167397e5f505a887955c73ec26af9b836e06cdf47d4c8f0b60034e7e3ff"
    ]
  },
  {
    "id": "cv26-2d999c1afcf33cef",
    "text": "No es podia moure en el rogle d'aigua i fang on feia la seua vida sense topar alguna cosa que li la recordara.",
    "sentenceIds": [
      "9d0bc57559d0d05d288c1165b89091576601440cce4964c68c466faecc65ea05"
    ]
  },
  {
    "id": "cv26-b1063770d4dddd64",
    "text": "Esquerra Republicana de Catalunya ha defensat que s'ha de trobar una oportunitat per assolir la independència.",
    "sentenceIds": [
      "30378e4c5696dd91c90d930514b0f7c88e9f849ca3c8cb6cab3e2b04a133fa5c"
    ]
  },
  {
    "id": "cv26-c4b56bce83a38be7",
    "text": "En el món del programari de propietat, cada traducció i recurs lingüístic creat està lligat al fabricant i a les seves restriccions d'ús.",
    "sentenceIds": [
      "dd736db522cb5fd4f053db68c01fd69dc5f7473c996f7db508b1199ab47dad53"
    ]
  },
  {
    "id": "cv26-5e6c6f376e2f48ff",
    "text": "Francesc Sanahuja i Toledano és un excursionista, alpinista i dirigent esportiu nascut a l'Hospitalet de Llobregat.",
    "sentenceIds": [
      "12278192df36f77d52f1d690ba727b0800f0bfd58aedd1e22868bf98be420339"
    ]
  },
  {
    "id": "cv26-df7f291b2e12cb3b",
    "text": "Molts van pensar que, pel fet de tractar-se d'un espai que abastava més enllà de fronteres de països, quedaria fora de tota regulació.",
    "sentenceIds": [
      "d069149ded85b9c2e63f84ba6650d72b9f0b8789948f50c0d4ab43a95ba86ca1"
    ]
  },
  {
    "id": "cv26-4d476e0a2149083e",
    "text": "Andreu Fortuny i Fàbrega va ser un violinista, compositor i director d'orquestra nascut a Sant Martí de Provençals.",
    "sentenceIds": [
      "78ec873d24004239774f7cfcbd1dd80e285939b463830a39d1451fd3c0d3c31a"
    ]
  },
  {
    "id": "cv26-7eecc5d2078594eb",
    "text": "Les universitats públiques catalanes ofereixen en llengua catalana menys del seixanta per cent de les classes.",
    "sentenceIds": [
      "66efcb77e143b1947e31390e731db36ee18a3e527c212cafaee5b575cefd8b13"
    ]
  },
  {
    "id": "cv26-edcce0d4245a7b0f",
    "text": "En tot cas els llibres hauran de tenir l'ISBN acreditatiu, i els treballs només podran ser valorats una vegada.",
    "sentenceIds": [
      "08d4693c11a8ff865de02316d1aeb472bff271da80ff370c8651015a745ce06c"
    ]
  },
  {
    "id": "cv26-ecdaa2343e1a1833",
    "text": "Gràcies a la disponibilitat del codi font, el programari lliure garanteix una independència respecte al proveïdor.",
    "sentenceIds": [
      "7e2659f1f8a49d5ac62b1a63c85f13f4971ac550f89b32471cec081285d3e3a6"
    ]
  },
  {
    "id": "cv26-7749f831194e30c9",
    "text": "Apunta el sis, trenta-quatre, setanta-cinc, vint-i-tres, trenta-set com a telèfon de la Clàudia Ladron De Guevara.",
    "sentenceIds": [
      "d2ba310840173fe7486f68511112b2e907fbf4007ddab51c11cbb2b594a3fe0e"
    ]
  },
  {
    "id": "cv26-53f0da69deaca3c2",
    "text": "Els subscriptors es poden subscriure per a missatges específics en temps de compilació, en temps d'inicialització o en temps d'execució.",
    "sentenceIds": [
      "a9cf1ff96a28f7c89bae567b7819e8457d34542c757788bdf7c8274c58238df4"
    ]
  },
  {
    "id": "cv26-e24640c424cdbde8",
    "text": "Doncs perquè la societat, els treballadors i les empreses, han produït béns i serveis que els romans no produïen.",
    "sentenceIds": [
      "9a9d69d1e08f56b70374d5efe54ed33be847eac8a23f6c0a7511f7e1d370beda"
    ]
  },
  {
    "id": "cv26-beab5691b6ebcb94",
    "text": "En totes les indústries hi ha factors disruptius que ocasionen que alguns fabricants surtin del mercat i que n'apareguin nous.",
    "sentenceIds": [
      "5963111d6a2e72a57f8000427afde0fa7795453e19b72a2e2269fcd5ddda1b89"
    ]
  },
  {
    "id": "cv26-70ee6bcd911af0b3",
    "text": "Exigeix paciència de tracte i és agraïda al mos si anem desengranant-la amb lentitud fins a omplir un plat soper.",
    "sentenceIds": [
      "42238b9f883e7c6260f992319bcc19e32227e26c1e8450fb464eed754db5fc62"
    ]
  },
  {
    "id": "cv26-2d5f735689df3d47",
    "text": "Mira'm quina és la millor manera d'anar del carrer de la Mare de Déu dels Desemparats al carrer de les Carretes.",
    "sentenceIds": [
      "c52a088306d440ebcb7f4297bf4f4e4be681ea1bad121bc4b885315b78fc4d4d"
    ]
  },
  {
    "id": "cv26-84a3fdbe06eb9260",
    "text": "Jacint Barrera i Arenas va ser un professor, naturalista, meteoròleg, farmacèutic i esperantista nascut a Teià.",
    "sentenceIds": [
      "adfe4e9b71951e847b633c35b759f6bce072713200c9c32a149e1020c926e57e"
    ]
  },
  {
    "id": "cv26-89dc959f0feb2e9e",
    "text": "Crec que venia un cop l'any, es posava en una classe i, un per un, anàvem desfilant perquè ens fes unes preguntes.",
    "sentenceIds": [
      "39b3906a72ae8bb00ff080cb0e64c980ac3ee64e46a0389a486711b52b3117be"
    ]
  },
  {
    "id": "cv26-f438a7d5abec56cb",
    "text": "Pere Gil i Babot va ser un comerciant, empresari, banquer, mecenes i col·leccionista d'art nascut a Tarragona.",
    "sentenceIds": [
      "3ecf2b88731d30e244c17c147838313edd96dc24b9b8870dc8214e07ed2bb25f"
    ]
  },
  {
    "id": "cv26-eb0c1235d8b2d5f2",
    "text": "Durant els anys seixanta i part dels setanta era habitual distribuir les aplicacions juntament amb el seu codi font.",
    "sentenceIds": [
      "53529c72d2ca9f596652d574af3b145b7cb0d67d8591d73fbf9eb0035f5f71e3"
    ]
  },
  {
    "id": "cv26-b902ea9fbd7f60be",
    "text": "Els episodis se centraven en l'eclosió de la pubertat dels protagonistes i sovint incorporaven un ensenyament.",
    "sentenceIds": [
      "536adb841ef9ee6afa4fb3b9d786d1cb5680f74c203c9ac1dbb77c6b496234d3"
    ]
  },
  {
    "id": "cv26-510671123944ac32",
    "text": "Per exemple, les banderes de la Unió Europea i de l'ONU, codificades amb les parelles EU i UN, respectivament.",
    "sentenceIds": [
      "2e3e60f1163ebe8fab76bb21076921bd46d152d21a4dad0ada0c64ab2cd2207c"
    ]
  },
  {
    "id": "cv26-77c03884eb4ef17f",
    "text": "El mòdul Calc s'ha ampliat per a funcionar amb fins a seixanta cinc mil cinc-centes trenta-sis files de dades.",
    "sentenceIds": [
      "be6b7013943b621847ba1076b10a7220aef96243e16255d72a11523defcbcec8"
    ]
  },
  {
    "id": "cv26-415c0f41c9cfa175",
    "text": "El programari lliure ofereix una transparència total, i permet als governs fer llurs pròpies auditories de seguretat sobre el programari.",
    "sentenceIds": [
      "f981a7cb67478efb8413f3b62053165d4a315f7f8198f89387faeb8cfc8c051e"
    ]
  },
  {
    "id": "cv26-ef84d0262c470f18",
    "text": "Joan Caball i Subirana és un coordinador nacional d'Unió de Pagesos de Catalunya nascut a Santa Llogaia d'Àlguema.",
    "sentenceIds": [
      "2a84257d6399976b68a044f73503bf95b57d3cae0b958fb53c7e10db6ff8663b"
    ]
  },
  {
    "id": "cv26-e72c26b0f71d138a",
    "text": "La majoria dels solars sense explotar de la ciutat estaven en un procediment d'execució hipotecària o no tenien cap valor.",
    "sentenceIds": [
      "5d16f89a789da35dc621b4ef83e1a31b125537015a63bca2c3f76fd67109b6aa"
    ]
  },
  {
    "id": "cv26-270a99fff2ee1944",
    "text": "Li diu el senyor notari que davant de l'increment del protocol no té més remei i que ha de posar un nou escrivent.",
    "sentenceIds": [
      "5bd2b6c09c13552e008b00cf8984d3d95380c7d9de73dc91a262d9f3aa4a563a"
    ]
  },
  {
    "id": "cv26-797064c2e5ba4b0b",
    "text": "A escala mundial les darreres xifres són de cent trenta-quatre mil vuitanta-vuit casos confirmats i quatre mil nou-cents seixanta-quatre morts.",
    "sentenceIds": [
      "fefb7bb3460515e0b683c2165803f875079ae102d1c354ce4b31ec3dc4feff96"
    ]
  },
  {
    "id": "cv26-336116645c7f9312",
    "text": "Avui comença una nova etapa amb canvi de format, una pàgina renovada que inclou més continguts i noves seccions.",
    "sentenceIds": [
      "4d88eb15d81795c78a0c766ba98f683ac1a424ac3f1367c23eb1aa9b2e989a51"
    ]
  },
  {
    "id": "cv26-fc992e5d80ba61cd",
    "text": "La part receptora de la comunicació haurà de respondre i ambdues podran establir un calendari o pla de negociació.",
    "sentenceIds": [
      "23ea3b7605120eba032e0ab3c61141594227f070554d7cf109246bc013f91e42"
    ]
  },
  {
    "id": "cv26-a93e91d9afd5439c",
    "text": "Rússia, amb nou milions sis-cents trenta-sis mil vuit-cents vuitanta-un casos i dos-cents setanta-cinc mil cent noranta-tres morts.",
    "sentenceIds": [
      "ec32a16d43548335107fc6c7a3b95804d845905b3514c67d9a1f0c40274c5ba2"
    ]
  },
  {
    "id": "cv26-480193913b4e7ee3",
    "text": "La música popular romanesa va influir en el seu ús poc convencional de la variació rítmica i el color instrumental.",
    "sentenceIds": [
      "e55f2880d68cf69710091ce8e92c5e21a66622a843a154ad18148a7ff96fce96"
    ]
  },
  {
    "id": "cv26-da5225c4a8546d07",
    "text": "Rússia, amb quatre milions set-cents setanta-un mil tres-cents setanta-dos casos i cent vuit mil cinc-cents vuitanta-vuit morts.",
    "sentenceIds": [
      "db44c410fdb794e42bf92ed49f60981983a23204bfc738cedb2f2f3ed827a6c6"
    ]
  },
  {
    "id": "cv26-d1923337aa43fdf1",
    "text": "Es tracta, habitualment, d'empreses que han impulsat projectes de programari lliure i en són titulars dels drets d'autor.",
    "sentenceIds": [
      "0c4274f3f55e919ae49d9db03cfb4df7f1c2d187bb2ff449bd62ed93c6b6ec64"
    ]
  },
  {
    "id": "cv26-d8a3a39dd383cf04",
    "text": "Els i les aspirants disposaran d'un termini màxim de quaranta-cinc minuts per contestar les preguntes formulades.",
    "sentenceIds": [
      "a89f94dc27360fc02f132dcd3744aba9a31bcf82aad880ff39367a380516de40"
    ]
  },
  {
    "id": "cv26-8d21028d8c728d98",
    "text": "El més destacable és que permet l'ús i explotació de l'aplicació, en forma de programa o codi, sense cap mena de limitació.",
    "sentenceIds": [
      "3ff2dee64c9e02d8b4f65fad108ef010b0562b39c35a42c4ebc9593f937684b3"
    ]
  },
  {
    "id": "cv26-b5e600117944b18e",
    "text": "Joan Evangelista Jarque i Jutglar va ser un teòleg i periodista fundador de \"Catalunya Cristiana\" nascut a Barcelona.",
    "sentenceIds": [
      "55cc1faa1ce94d3af873abfdbab336d7fbc418bc651c8f17788028b529e3ae76"
    ]
  },
  {
    "id": "cv26-f391b2b24029f8d0",
    "text": "Johnson va conservar algunes persones designades per Kennedy, algunes d'aquestes al llarg de tota la seva presidència.",
    "sentenceIds": [
      "b96917f9531fada85775d090ef08e0a900f7e29e984a9992df6762e88fdfd3e9"
    ]
  },
  {
    "id": "cv26-34d7759da9e420c4",
    "text": "Josep Maria Carreras i Puigdengolas és un economista, professor, urbanista i funcionari nascut a Vilanova i la Geltrú.",
    "sentenceIds": [
      "c9ecb8eff1f952baa26d2903dc04822f078a33beb9c6fba2ed4bbcec89f328ed"
    ]
  },
  {
    "id": "cv26-de487497f4fec917",
    "text": "Encara que era una mica pesat pujar després el prat amb la roba molla, no deixava de ser un esdeveniment social.",
    "sentenceIds": [
      "84e8a2e168835cfc0bb5b3b2236711f873a365cce799cb434cd995b092786518"
    ]
  },
  {
    "id": "cv26-30673ac89890f3a1",
    "text": "El mòdul Calc s'ha ampliat per a funcionar amb fins a seixanta-cinc mil cinc-centes trenta-sis files de dades.",
    "sentenceIds": [
      "b4929390e4a9d8e30a040c3ba4df3075203c9d92a819d2c55ceccf7dfa6faf66"
    ]
  },
  {
    "id": "cv26-5a1edb470f67f402",
    "text": "Francesc Pérez-Cabrero i Ferrater va ser un compositor de sarsueles i director d'orquestra nascut a Barcelona.",
    "sentenceIds": [
      "35eb929b9d6081699910fbf78b34ef77a71c540584823b7b76335c0bd7e073e4"
    ]
  },
  {
    "id": "cv26-d5ac3f45e95970fa",
    "text": "Mira'm quina és la millor manera d'anar del carrer de la Mare de Déu dels Àngels a la placeta de Miquel Pallés.",
    "sentenceIds": [
      "c6d9da77c6998c2e8514fcd02fc87c7a3b0eb52920a26d0b84cbb77fdc94a1c1"
    ]
  },
  {
    "id": "cv26-1be1963f11eceb4f",
    "text": "Com a resultat, es va disposar de menys diners per donar suport a la programació d'entreteniment de xarxa de ràdio de qualitat.",
    "sentenceIds": [
      "006cb0e55c70d6d6388cbd96aaf1538f1322399a0f5ad08d4e9062db8b0c9913"
    ]
  },
  {
    "id": "cv26-eff94356aeceb6a7",
    "text": "No ens equivocaríem si parlàvem d'una profunda empremta, d'un rastre detectable en el treball temàtic i motívic.",
    "sentenceIds": [
      "666d9d22ce0e0d91651247776d164bbc20722d89c7b1961f3dfa4f0287ad0bc7"
    ]
  },
  {
    "id": "cv26-27d5b1d611bc636d",
    "text": "Insilicos desenvolupa una aplicació informàtica científica per a proporcionar un programa per al diagnòstic de malalties.",
    "sentenceIds": [
      "2cbfbf8348e775c2570a18571430f05d0f342770389f6bb72433217c6ef2f7dc"
    ]
  },
  {
    "id": "cv26-83620ac00e129062",
    "text": "La web ha tingut un paper central en el creixement d'Internet i, conseqüentment, en la difusió del programari lliure.",
    "sentenceIds": [
      "fa0dd81ef80b67a3f37c09ba94442bb91ba4d16acabe985e63afdfa8d92de90a"
    ]
  },
  {
    "id": "cv26-9509013affc97129",
    "text": "Les despeses de consultoria i serveis equivalents no podran excedir el cinquanta per cent de les despeses totals de coordinació.",
    "sentenceIds": [
      "0a18d94253b63f2e36699543d7a1d4479e720e1bca724f85275f587ebb92e74d"
    ]
  },
  {
    "id": "cv26-b1c5972b9e439b84",
    "text": "Josep Maria Figueres Artigues és un historiador i professor d'història del periodisme nascut a Vilanova i la Geltrú.",
    "sentenceIds": [
      "d434a8cd0b2d2b4eed359966d6f1b7c8a82fa2c3e6f10cfb2fe9e33ad50ef10c"
    ]
  },
  {
    "id": "cv26-773ed6091a30d9f2",
    "text": "Bufa amb mètode implacable i no para fins que deixa la natura derrotada i una collita de deixalles desfermades.",
    "sentenceIds": [
      "5f9fe78daee1fbeca62d9e1e8299b23f154865dbf2ca75b15f7a3784ea164ed8"
    ]
  },
  {
    "id": "cv26-5ec510e6255f6c2a",
    "text": "A més de publicar el codi font calia crear un lloc a Internet per organitzar el desenvolupament de tot el projecte: naixia Mozilla.",
    "sentenceIds": [
      "7aa7c5689b18dc0fe1732d64d73cbb060f22874a39f29ea2603ee8cab5356658"
    ]
  },
  {
    "id": "cv26-71fb5c1610ea59ee",
    "text": "Rússia, amb quatre milions sis-cents cinquanta-set mil vuit-cents vuitanta-tres casos i cent tres mil sis-cents un morts.",
    "sentenceIds": [
      "47576cd1a39fdf4e7f06665b23d9a0fa4a0bbbc8a1d440ee1de251ff51df7ea9"
    ]
  },
  {
    "id": "cv26-be2ed939bcb26e13",
    "text": "També s’ha habilitat el número nou set tres sis zero tres vuit cinc dos per avisar quan es trobin animals abandonats.",
    "sentenceIds": [
      "52e4b757f24592e4a38daa2f974356a6feba848936791743efa33c4146deeaf1"
    ]
  },
  {
    "id": "cv26-b1f828d3939cbb95",
    "text": "El jurat podrà declarar desert el certamen si considera que les peces presentades no tenen la qualitat suficient.",
    "sentenceIds": [
      "01e029cf5501988b171c50a42805b22e4bf1dc0cecf7dc089f7a7c742b0e5f25"
    ]
  },
  {
    "id": "cv26-7120fd0bdda8870b",
    "text": "L'any dos mil vuit, l'última vegada que havíem renovat el nostre lloc, sembla el segle passat a escala tecnològica.",
    "sentenceIds": [
      "e34269903a5da06f3dde0a92009f443260eee97eba9a00d09860c53ed56c9ff0"
    ]
  },
  {
    "id": "cv26-1ef5614877470bf5",
    "text": "Gràcies al procés continuat de millora en què està sempre, ja disposa de dos mil dues-cents regles de revisió.",
    "sentenceIds": [
      "0d4e7490ff8a9cbf57a01a1ba711d8e4a482c30fb39a5b128910f87d46d9984c"
    ]
  },
  {
    "id": "cv26-c23d57170f119afa",
    "text": "Mira'm quina és la millor manera d'anar de la plaça de Carme i Enriqueta Soriano i Tresserra al carrer del Cardenal Reig.",
    "sentenceIds": [
      "bad3e675d45332759420a433e015004cac2c71b20ca6c7319d6bc5092ac2cc7b"
    ]
  },
  {
    "id": "cv26-8f832b185539d746",
    "text": "Els seus importants mediadors, la bradiquinina i la cal·lidina, són vasodilatadors i actuen sobre molts tipus de cèl·lules.",
    "sentenceIds": [
      "dddc187dcb46767225938459794fdc46987db65f6ecc59426e3a04a1343f3968"
    ]
  },
  {
    "id": "cv26-9640c4a01dfc4b92",
    "text": "Els índexs de victòries fàcils en eleccions parlamentàries són extremadament altes quan les comparem amb normes internacionals.",
    "sentenceIds": [
      "31641de8fd79d82ada3881f724822577313656bacdff91ced8c849ad9fcf9b63"
    ]
  },
  {
    "id": "cv26-bdc7ea964c633cd8",
    "text": "Ramon Cotrina i Puig va ser un escriptor, traductor, sociòleg i activista polític nascut a Sant Joan de les Abadesses.",
    "sentenceIds": [
      "05f6f185d6e8e2b3f50d61e728fcc298e45a3ab428217b72340d2c0420d98351"
    ]
  },
  {
    "id": "cv26-408288f39042b6c1",
    "text": "No es pot negar a ningú fer ús del programa amb una finalitat determinada, com per exemple comercial o militar.",
    "sentenceIds": [
      "af50cdfc5429a7af2aacae6a042334fea0ed10f6fab75d4d5f702138f9ade28f"
    ]
  },
  {
    "id": "cv26-28e15db2668a60da",
    "text": "Aquestes xifres signifiquen un augment del quaranta-cinc per cent dels beneficis en comparació amb el dos mil vint.",
    "sentenceIds": [
      "4cbeb93c237ec2251824c50393f2f59bd66d5e477d40a9db9de9cdb371dde5fe"
    ]
  },
  {
    "id": "cv26-cf36028f76dc8347",
    "text": "La sèrie discontinuada de caixmir presentava efectes d'impulsió amb un patró de caixmir en recintes d'estil original.",
    "sentenceIds": [
      "09231178f013232d49a1700258bf904ec7c31492a5d6e710c7f1b3690023fa6d"
    ]
  },
  {
    "id": "cv26-20712207e2461591",
    "text": "Les patents són la concessió d'un monopoli sobre una invenció durant un període limitat de vint anys, després del qual tothom en pot fer ús.",
    "sentenceIds": [
      "e4aea4a4c8749c2c26b5bb4af7509382ca03c9707ad5c879e6c2513142d7e713"
    ]
  },
  {
    "id": "cv26-8ab0c1b3137b83e0",
    "text": "Regne Unit, amb deu milions tres-cents setanta-nou mil sis-cents quaranta-set casos i cent quaranta-cinc mil quatre-cents vint-i-quatre morts.",
    "sentenceIds": [
      "fc6d1e9153308cdf8820498228c06944072b009e8beaa0844ac5d9498f85eb68"
    ]
  },
  {
    "id": "cv26-c864ea41d615c77d",
    "text": "Josep Xifré i Casas va ser un negociant, industrial, comerciant, financer, filàntrop, mecenas nascut a Arenys de Mar.",
    "sentenceIds": [
      "de8f32d797688c19ae7f4edc1e4b8faf4acc8008f81e45e9d654170cf7994fca"
    ]
  },
  {
    "id": "cv26-8ef930bb383b212f",
    "text": "Aquest tipus d'empreses representa l'àrea principal en què s'està concentrant el desenvolupament del negoci del programari lliure a Espanya.",
    "sentenceIds": [
      "0c384516c0255ccdb025944888ba7d1adcbd392468aef06958bbc1699a6f6e4f"
    ]
  },
  {
    "id": "cv26-c54a1a1f9ac11573",
    "text": "Cinc mil set-cents vint-i-tres nou mil dos-cents cinquanta-tres nou mil nou-cents vuitanta-set dos mil tres-cents seixanta-vuit cinc mil cent trenta-cinc...",
    "sentenceIds": [
      "e43ed6046a86384dda6bc2ace4fdfa5f5a8565473d15ff4d9f407b81abee19b6"
    ]
  },
  {
    "id": "cv26-21190591baac5436",
    "text": "És bon senyal, en aquest sentit, que cada cop ens costi més trobar nous llocs d'interès per a llistar en el directori.",
    "sentenceIds": [
      "ce484ce1ec32a6f00520fcbde739d401e4772764278bcea0f9291f17cc9fbf6f"
    ]
  },
  {
    "id": "cv26-1d0f84ade85ce590",
    "text": "Des de maig a Sant Miquel, pastor d'ovelles vull ser; però de Sant Miquel a març, que les meni l'amo del ramat.",
    "sentenceIds": [
      "fca1ffe6db9e3c4e04b32a0e6a507f16fc1d040382320eb29c3328c5a50f4da1"
    ]
  },
  {
    "id": "cv26-123753846c88d96e",
    "text": "Afegeix a l'agenda el número de la Fàtima zahra El Amrani: sis, vint-i-set, tretze, cinquanta-cinc, seixanta-quatre.",
    "sentenceIds": [
      "bc355efb6afe20fc946d94128a6e68ffba9ec8970e4bd9c1625257cbc064a8aa"
    ]
  },
  {
    "id": "cv26-3274e68b2a4e6113",
    "text": "Rostit sense vi no val un comí, pilota sense pebre no val un senabre, estofat sense xocolata no val una patata.",
    "sentenceIds": [
      "7577e43dbf2a2053bda5de3ce6188b64a409718f09967a1d0b7ce93d2d78f30e"
    ]
  },
  {
    "id": "cv26-b68b653aa20681fe",
    "text": "Per fer front als xocs, es va aplicar una política fiscal expansiva i van caure els ingressos provinents de privatitzacions.",
    "sentenceIds": [
      "1070c86557010758da906962c3455f6906741fbf4b2d43467a624ebca8d2da84"
    ]
  },
  {
    "id": "cv26-14fd0b47cdb7f9f1",
    "text": "Posteriorment, va deixar d\"estudiar química però va seguir interessat en aquest camp durant tota la seva vida.",
    "sentenceIds": [
      "56015662aa4bef24aa3c570608856f109cc5245ae3036750fd1e35eea5b8ab63"
    ]
  },
  {
    "id": "cv26-ab91e25a0ef54d23",
    "text": "Reclamem un turisme cultural, d'esports i de caràcter familiar i d'aire lliure que estiga arrelat al territori.",
    "sentenceIds": [
      "52a708da89820bbb1c988eba113ad2250db1f91605482c5235ac4f1ff758bffa"
    ]
  },
  {
    "id": "cv26-483b67c17360461c",
    "text": "Mira'm quina és la millor manera d'anar de la passatge del Rector Oliveras a la placeta de la Marquesa de Caldes de Montbui.",
    "sentenceIds": [
      "989c63977a15cde4aec07720b67bba44633adf5def09bb34a11864e5ad0518f2"
    ]
  },
  {
    "id": "cv26-d9305e44696315ff",
    "text": "Algunes d'aquestes idees han estat adoptades posteriorment per creadors de continguts digitals com ara música, vídeo o llibres.",
    "sentenceIds": [
      "55945ee019fa1223dd30d666be7da07333916e4d046d95c8b3f69138622e9afc"
    ]
  },
  {
    "id": "cv26-76bc5102f3f6a00f",
    "text": "Algunes caixes fortes de paret tenen portes antifurts encastades amb frontisses ocultes que protegeixen de robatoris.",
    "sentenceIds": [
      "b3f1c8aad78103f346d5f525ad5b8ba43537fa6f4a29390fbf7f0fc4588cb985"
    ]
  },
  {
    "id": "cv26-802069481733eed9",
    "text": "En la gestió tradicional de relacions públiques, el control de danys suposava la supressió de la informació pública.",
    "sentenceIds": [
      "c051637bab5d150206cc0f8a148129196e143344a0caefc12a0e3903054bcc64"
    ]
  },
  {
    "id": "cv26-6e6af2d0095e0e56",
    "text": "Regne Unit, amb vuit milions quaranta-sis mil tres-cents noranta casos i cent trenta-set mil quatre-cents disset morts.",
    "sentenceIds": [
      "9deb12fb7f8a27b8430e031e685b8a608aa958f4dd392671043a1a6dcc557b6f"
    ]
  },
  {
    "id": "cv26-d1f4717148e38032",
    "text": "Des de maig a Sant Miquel, pastor d'ovelles vull ser; però de Sant Miquel a març, que les mene l'amo del ramat.",
    "sentenceIds": [
      "4058682c3af5fcf43edfa5f4ada1029ac74c28fe13c97277d062b9fe9a820d50"
    ]
  },
  {
    "id": "cv26-aa58e65bbb17591f",
    "text": "El mateix instint que el feia recelar li féu avançar la mà, que va alçar lleument un costat del misteriós domàs.",
    "sentenceIds": [
      "7266a9e30f6dc333a1f417582bf2ed1ebbd667662b2efca9bc3921091dbf9894"
    ]
  },
  {
    "id": "cv26-0d0171823b1a06cf",
    "text": "Núria López Bigas és una investigadora en genòmica computacional del càncer nascuda a Monistrol de Montserrat.",
    "sentenceIds": [
      "7db156472dfde7b9d58f92842a760225e1eb1d8c7ea68d54c881b0bdd33a7489"
    ]
  },
  {
    "id": "cv26-3772d97a27b2500a",
    "text": "Des del juny del dos mil tretze funciona a la web de Softcatalà un nou corrector gramatical i d'estil de català.",
    "sentenceIds": [
      "208054aa56fe6645168892aa44c994cb445ed02f5a1cb411ddb468b772dc8ee1"
    ]
  },
  {
    "id": "cv26-9e1efc6d7ebac269",
    "text": "Francesc Murgadas i Bardí és un biòleg i periodista especialitzat en gastronomia nascut a Vilanova i la Geltrú.",
    "sentenceIds": [
      "039db383ad9df796c86bb52aebf04a4edd99efe5ecc8199a9ea4e4f244533ffd"
    ]
  },
  {
    "id": "cv26-a9f03efafac76b80",
    "text": "Es creu que el nom \"drone\" (borinot, per un tipus d'avió) deriva de \"Queen Bee\" (abella reina, un altre avió).",
    "sentenceIds": [
      "bf608744bc97f36a67341eed0141ff3640f488d0b13014d01c98533b844eb640"
    ]
  },
  {
    "id": "cv26-8a4a4433a4796187",
    "text": "A Espanya hi ha poca indústria pròpia de programari estàndard, i gairebé totes les aplicacions de consum massiu es desenvolupen a altres països.",
    "sentenceIds": [
      "a45e4be9a2d7bbaa879c3a0398ee81a6c308ace83c5ea7c072211499b0f6e2c4"
    ]
  },
  {
    "id": "cv26-b875dd262e899a9f",
    "text": "Mitjançant el Programari Lliure es disposa de solucions per a la gran majoria dels problemes que pateix en José.",
    "sentenceIds": [
      "80a89b43d7be6e26cb631bcb894db067c5a7b68efcd11ddf03d08e0e9df37780"
    ]
  },
  {
    "id": "cv26-cad82aa83ccb1d62",
    "text": "dues persones de l'equip parlen sobre un motor de carreres automobilístiques durant un espectacle de carreres automobilístiques.",
    "sentenceIds": [
      "bfec99ee81a1ca1e7bcf745329a625b56d0a3cace45b90cfaa63294fb6f5614d"
    ]
  },
  {
    "id": "cv26-789493e076dcaf2a",
    "text": "En tot cas, l'informe clínic pertany a l'esfera íntima de les persones treballadores i com tal ha de ser protegit.",
    "sentenceIds": [
      "57a68414bd02a222680b1f876ebae02a063acdde9e15f9356724fc91387bb614"
    ]
  },
  {
    "id": "cv26-d3d2a4c95e950515",
    "text": "Aleshores, hi havia cent trenta-quatre mil persones en aquesta situació i ara ja en són cent setanta-quatre mil.",
    "sentenceIds": [
      "c72de21c393dd728d838b617260040042bed3069e011c1d663f96d804956bee7"
    ]
  },
  {
    "id": "cv26-5fb042a001e0ed39",
    "text": "Regne Unit, amb nou milions dos-cents quaranta-un mil nou-cents setze casos i cent quaranta-un mil cinc-cents vuitanta-vuit morts.",
    "sentenceIds": [
      "2c38a0db9a96d4a29191d0b60e15a63e5af480dba8f1ba5012a81a2884ccb262"
    ]
  },
  {
    "id": "cv26-73e0065b8004b215",
    "text": "Aquesta proposta serà notificada al sol·licitant qui tindrà un termini de deu dies per presentar-hi al·legacions.",
    "sentenceIds": [
      "20673861ee7fe9d34a8d8d58dd04708e47a11eb2f214930d2af7fdc9284cab8c"
    ]
  },
  {
    "id": "cv26-d8ddbd00a185dcb9",
    "text": "El president podrà expulsar del local a aquelles persones que impedeixin el normal desenvolupament de l'escrutini.",
    "sentenceIds": [
      "57937e55763516e02268e203b5ab0189cf82c22ce386c71c4524390a59f1bd7a"
    ]
  },
  {
    "id": "cv26-d18b581b1f519959",
    "text": "Quimet ha acompanyat Anna a ca l'oncle Joan, que ja estava una mica preocupat per la tardança de la seua neboda.",
    "sentenceIds": [
      "4a32ecb914332c1307949087ff3f2a8deea01a105c5a3a9f1d012f1da48b9fda"
    ]
  },
  {
    "id": "cv26-6322c9a518e605d2",
    "text": "Mira'm quina és la millor manera d'anar del carrer de Lluís Nicolau i d'Olwer al carrer del Naranjo de Bulnes.",
    "sentenceIds": [
      "ec1e4a5e609a2b0af8b7f97def4902db6ceda207587f076bd8177ee9dad3b743"
    ]
  },
  {
    "id": "cv26-4ec58630300ccfbf",
    "text": "Havent dinat, cap allà a les dues, està prevista la visita al taller i a les vuit del vespre, el vol de tornada a Barcelona.",
    "sentenceIds": [
      "abb85ec4c8b3794cd74c3ddb7f9122a15440f601d92062dfcd71d0779ddc215d"
    ]
  },
  {
    "id": "cv26-c03460dc0ffa639d",
    "text": "Mira'm quina és la millor manera d'anar del carrer de Felip Bertran i Güell al carrer del Doctor Ribas i Perdigó.",
    "sentenceIds": [
      "dca1af05a7df96d81150dfb82eac0995849c9a343a71bb281f4bd3ea9fabb0e5"
    ]
  },
  {
    "id": "cv26-deeb4191e38d3df1",
    "text": "Només ara, quan la situació ja és especialment greu, sembla que hi ha una certa reacció rebel cap a la metròpolis.",
    "sentenceIds": [
      "52aa08e71703af662e8baaf85cca3a05c158101de37d2ae5d039c4da6967de7f"
    ]
  },
  {
    "id": "cv26-38418a3d1b1763ed",
    "text": "Imaginem-nos que només pretenem poder votar als nostres ajuntaments i juntes de districte en horari d'oficina.",
    "sentenceIds": [
      "04b8489e239d05ddc4b3a9b15201b4c7bda3f66652b8398dd027df75103f2c7f"
    ]
  },
  {
    "id": "cv26-c5059d5c8f587d25",
    "text": "Entre la superació de la part teòrica i la realització de la pràctica, no podran transcórrer més de dotze mesos.",
    "sentenceIds": [
      "1fd1c46c5a5cbad01935c50b8cfd06f77e25db04fa3898927717ba908707d3e1"
    ]
  },
  {
    "id": "cv26-a23c4bb293de80ad",
    "text": "Aquest cop en DVD, encara que més endavant està previst fer la versió en CD-ROM i també la de seixanta-quatre bits en DVD.",
    "sentenceIds": [
      "d0276f3a3253e25fb86b1d4f3503f381abd845074c5124375165632189a40190"
    ]
  },
  {
    "id": "cv26-6cbeca36c8488d05",
    "text": "L'arxivament ajuda a gestionar la safata d'entrada i desa el correu en un nou sistema de carpetes d'arxivament.",
    "sentenceIds": [
      "2e82d9804be3880567010715df2c999e0212899b9c3ce63a304dc59d49f9f7b3"
    ]
  },
  {
    "id": "cv26-e8ccb8cf655ca27e",
    "text": "Reserva'm un bitllet de tren per anar a Sant Salvador de Guardiola el disset d'octubre a tres quarts de dotze.",
    "sentenceIds": [
      "26d0e88a53f3a2db0182d0f283055950a6252ad9fa89540a828d896add9c544c"
    ]
  },
  {
    "id": "cv26-2d3676facb0a7023",
    "text": "El Ple del Consell es reunirà cada tres mesos i podrà celebrar les seves sessions en qualsevol lloc de Catalunya.",
    "sentenceIds": [
      "2f8021479556bcf61e86a6ad5d1c64234535220e055b8298b2bc08e54bbd23d6"
    ]
  },
  {
    "id": "cv26-eab2b5020ce52355",
    "text": "Les dutxes ens queden a uns dos-cents metres, però el camí és absolutament pla, cal travessar una gran esplanada.",
    "sentenceIds": [
      "090ce94138850301d44d7883a041410ec12ce88c9b3214fbdd229cce41356df4"
    ]
  },
  {
    "id": "cv26-1af58cd20a4ce36e",
    "text": "Rússia, amb deu milions quaranta-sis mil quatre-cents cinquanta-quatre casos i dos-cents noranta mil sis-cents quatre morts.",
    "sentenceIds": [
      "6f8ee8a237710332688ad1b1c410ecef3db6c4f7bc960363d3a529a03d99b8ab"
    ]
  },
  {
    "id": "cv26-a346fd8528d0e7fc",
    "text": "S'ha millorat la barra d'eines de cerca amb una llista desplegable de tipus de cerca per a agilitzar la navegació.",
    "sentenceIds": [
      "93b0d116c7474ec53552791dd463abac9fc4ec4c0b80a4228c1aef824c0875ff"
    ]
  },
  {
    "id": "cv26-8d2fca7285b5a2ef",
    "text": "El programari lliure és, probablement, l'única opció que tindran molts països en vies de desenvolupament per sumar-se a les noves tecnologies.",
    "sentenceIds": [
      "9407608cb064fe86a12d0e8c8d62966ba22cff4d34862e6822bd4f2e289c2afe"
    ]
  },
  {
    "id": "cv26-5aab8ac03817a90b",
    "text": "Jornada adaptada a l'horari d'obertura de les instal·lacions, el que pot suposar treballar en jornada partida.",
    "sentenceIds": [
      "c4ef1f52c4c82d88147372e853ef3f43e56a14c4d434b912c4330b2c81846fd4"
    ]
  },
  {
    "id": "cv26-45d8e99afe1a8bff",
    "text": "El codi font del projecte s'ubica en un servidor centralitzat, el qual gestiona un programari de control de versions.",
    "sentenceIds": [
      "67de10d0eeb27ef0d96954c8f658e9fb7d1ca174894b555e8afdf1899fd086dc"
    ]
  },
  {
    "id": "cv26-31946658da9072eb",
    "text": "A partir d'aquesta versió es pot fer la instal·lació i configuració del sistema completament en aquesta llengua.",
    "sentenceIds": [
      "a08207d9408cbbce86130cadc0cffd20cb37226dae27ee290a5686610d8e2501"
    ]
  },
  {
    "id": "cv26-ce2958c7f8792cda",
    "text": "Les operacions paral·leles són, per tant, cent noranta-un mil nou-cents trenta-dos multiplicat per dos més nou.",
    "sentenceIds": [
      "0f4651ffa380b589850a7e97d4cbe88947e0ffa7082432a4b24b8102bff22378"
    ]
  },
  {
    "id": "cv26-589fd40fc71fcb6b",
    "text": "Rússia, amb sis milions set-cents vuitanta-cinc mil tres-cents setanta-quatre casos i cent setanta-set mil sis-cents catorze morts.",
    "sentenceIds": [
      "63c1bb268a42f3ca236399294778144a8b9e474e21d5abfab3a65a77f8842e60"
    ]
  },
  {
    "id": "cv26-f90ea4b146dc7b1b",
    "text": "Els factors de risc mediambientals inclouen el tabaquisme, l\"exposició al plom i altres tipus de contaminació de l\"aire.",
    "sentenceIds": [
      "407f3f0f87946373384b1a0274fe8a198283ac3aba14eda558a5544676a725e4"
    ]
  },
  {
    "id": "cv26-90c21cf98bb3e1df",
    "text": "Regne Unit, amb nou milions set-cents vint-i-un mil nou-cents setze casos i cent quaranta-tres mil cinc-cents cinquanta-nou morts.",
    "sentenceIds": [
      "e5c50770293c20c3fc134f4559171fa90728396f4f22be5b69e42d9f0abe2255"
    ]
  },
  {
    "id": "cv26-8e7875862b1e0ff0",
    "text": "Quina és la millor manera d'anar de la camí Vell de Santa Creu d'Olorda a Vallvidrera als jardins de Rubió i Tudurí?",
    "sentenceIds": [
      "555aa76a801c6e1301147dae660a98fa4f170026caef0f3530b78ba00917e900"
    ]
  },
  {
    "id": "cv26-0eeab59299d4afd5",
    "text": "Per tant, vam demanar a Google que durant la Diada mostrés un logotip específic per commemorar l'conze de setembre.",
    "sentenceIds": [
      "4d26d119f602f78ae6f895cd6be021e2e8e173e92c6b2a7eca6a4d274c975d4a"
    ]
  },
  {
    "id": "cv26-9bf1a848fb9885bd",
    "text": "Entre les contribucions de Graham a \"Cuphea\" es troben dos volums de la sèrie \"Monografies de Botànica Sistemàtica\" (Systematic Botany Monographs).",
    "sentenceIds": [
      "091daf8f1f9920d00f67b3799aa35de036b54795d161cdb7a22d129977a3ff15"
    ]
  },
  {
    "id": "cv26-6ec6bc4bcb5a1c34",
    "text": "El termini començarà a comptar-se des del sendemà a aquell en què adquirisca fermesa la resolució sancionadora.",
    "sentenceIds": [
      "07cb9f3be6f64911f8a2eaeb797f74a81596874f6f364db70388aced0a3d4f33"
    ]
  },
  {
    "id": "cv26-4c5676f83387715f",
    "text": "Així, si estem realitzant una creació combinant creacions de tercers, com per exemple un article, hem de demanar permís a l'autor original.",
    "sentenceIds": [
      "bd35df8802b6258b2d5bd8c6a29587c8dd23952dffb6d7b0e07265ce97c4cf1c"
    ]
  },
  {
    "id": "cv26-ec68d359ba2dd39f",
    "text": "Bonaventura Frigola i Fanjula va ser un compositor, director i professor de música nascut a Castelló d'Empúries.",
    "sentenceIds": [
      "11122fc7cf08278fbb6153bc1deef6f4727a12622df4c462814d3fd6916f8ce0"
    ]
  },
  {
    "id": "cv26-e4a5a4cc6384ca53",
    "text": "Altres productes temàtics de Morrigan inclouen làmines enrotllables i pòsters, samarretes i fundes de Capcom, entre d'altres.",
    "sentenceIds": [
      "a1d6d6545bfc654d79b5af0d09b62fbc9be93cbc73fdae2225ebeb6695b14293"
    ]
  },
  {
    "id": "cv26-72efc17ff3c85f19",
    "text": "Reserva'm un bitllet de tren per anar a Monells i Sant Sadurní de l'Heura Cruïlles el vint-i-tres de maig a les dotze.",
    "sentenceIds": [
      "b9a3feb70e97d911c9b733d989be5fac51ce77a0b151c31ef0cab94a7004d2a7"
    ]
  },
  {
    "id": "cv26-78c207470df994c0",
    "text": "De la terra pujava una olor fresca, de terra humida, que perfumava tot l'ambient amb eixa aroma característica.",
    "sentenceIds": [
      "99b9e9ae51da806329ffec443535cd284071cc5dd2283b3c9ab1d63a99293440"
    ]
  },
  {
    "id": "cv26-595f4bbbe364f3ab",
    "text": "Baix, a la plaça, els xics xisclaven com condemnats i la xarradissa de les dones pujava com un brunzit molest.",
    "sentenceIds": [
      "cf30127fc9f9aa9767f6fbf94cabced9257e9d03a32c09ec948e5cbe1544b968"
    ]
  },
  {
    "id": "cv26-bc02862b5f4a625f",
    "text": "L'èxit d'una pel·lícula als Estats Units es determina amb la recaptació del primer cap de setmana d'exhibició.",
    "sentenceIds": [
      "9591716d625a3703c9b4b62ae4a7cdf42be55bb582a72743c4bb085690b6b8e4"
    ]
  },
  {
    "id": "cv26-4419b8fe008a0bb8",
    "text": "Apunta a l'agenda el número de la Roma Ladron De Guevara: sis, noranta-nou, setanta-cinc, quaranta-quatre, zero, set.",
    "sentenceIds": [
      "466d0d19feb53bc95855646dc351b74dbf8c2c4b4b07be142bc3e27b15e4ef8f"
    ]
  },
  {
    "id": "cv26-5a0853442f2af6b6",
    "text": "Les marques solen justificar-se perquè un client pugui identificar, de forma clara, que un producte o servei prové d'un fabricant determinat.",
    "sentenceIds": [
      "0792ff9c4416afe4811097e47ffb2971b4b65ebf928822cc4d957e925ed698c5"
    ]
  },
  {
    "id": "cv26-96caa01e9c593ef9",
    "text": "Melcior Niubó i Santdiumenge va ser un dibuixant, caricaturista, pintor, Il·lustrador i animador nascut a Barcelona.",
    "sentenceIds": [
      "48f2f6321c4878f78e166c6b62b41b717449f56796ee0bc6a7971edb12149eda"
    ]
  },
  {
    "id": "cv26-263fb8701072b291",
    "text": "Mira'm quina és la millor manera d'anar del passatge de Santa Maria de Vilalba a la plaça de Miguel de Unamuno.",
    "sentenceIds": [
      "453404833955ecc5c9b78032befcdb0e70f3e1390b9873889042dca375e08a1f"
    ]
  },
  {
    "id": "cv26-b808ac4854925709",
    "text": "Quan arriba el fred de l'hivern, com que tenen els rebosts plens, no tenen necessitat d'eixir fora a gelar-se.",
    "sentenceIds": [
      "b0812902b058c382f3e1f102926246c3c55e24b4c6706613aaae62f84d2b89e5"
    ]
  },
  {
    "id": "cv26-b7484c425da637f2",
    "text": "Els tretze savis van acordar que farien una processó després del dinar de festa major, però que en dirien cercavila.",
    "sentenceIds": [
      "9ceb9ff3124fb94d774e2b9b28a5d53d527652e0730abc7fb9e9ac236c4835eb"
    ]
  },
  {
    "id": "cv26-3d5b5f20e86f026d",
    "text": "Mira'm quina és la millor manera d'anar del carrer de Dolors Lleonart a la plaça de l'Escultor Ramir Rocamora.",
    "sentenceIds": [
      "974b9161fe6ff5ce06000b75853abfdd7e166407ea47ca89d56e3d2f4bb156ca"
    ]
  },
  {
    "id": "cv26-a33f430320f1a251",
    "text": "Àgels Torrents i Rosés va ser una professora universitària, doctora en demografia històrica, investigadora nascuda a Sant Pere de Riudebitlles.",
    "sentenceIds": [
      "e6972b63fa6eba7a1de762833192c53c94c5308362376f5fd1dd331f93c158f6"
    ]
  },
  {
    "id": "cv26-53669137a16c1a27",
    "text": "Aquests ports són els primers a ser inclosos en un llançament de Debian sense estar basats en el nucli de Linux.",
    "sentenceIds": [
      "46c25c63be141adf6cacc49126ea6a3e3eaa4034d935c8ea1063ceaa7acded02"
    ]
  },
  {
    "id": "cv26-d9a9dbc579f58aaf",
    "text": "Regne Unit, amb set milions cent trenta-dos mil setanta-dos casos i cent trenta-tres mil vuit-cents quaranta-un morts.",
    "sentenceIds": [
      "6b5db407663b9949dc97728192420f49a4024cf739a327d5dabf69765874d49a"
    ]
  },
  {
    "id": "cv26-2a9ea2e8571ba587",
    "text": "Amb més de vint-i-cinc mil nou-cents noranta-tres contenidors, ja hi ha un iglú per cada cent noranta-cinc habitants.",
    "sentenceIds": [
      "5c059a09ad058125ab8143a2f49566e94a0786f367abd26e030267c2c2f56d1f"
    ]
  },
  {
    "id": "cv26-f9453e4b624236ca",
    "text": "Mira'm quina és la millor manera d'anar del passatge de Flaugier a la placeta de la Marquesa de Caldes de Montbui.",
    "sentenceIds": [
      "4cda91008233468080eb49d9fa269ad74e87ff1d36f0e525bb766ee85bb2ff36"
    ]
  },
  {
    "id": "cv26-359dbce5d21065b0",
    "text": "Afegeix a l'agenda el número de la Sofia maria Escuer: sis, vuitanta-set, quaranta-set, vint-i-quatre, zero, vuit.",
    "sentenceIds": [
      "32ffba059d9a6ac0f99c58cb3884f2ed25464b011beda3ac36d425d65bd742e4"
    ]
  },
  {
    "id": "cv26-7e6c54154cea8bcf",
    "text": "El noranta-sis coma cinc per cent fa servir Windows, el dos coma dos per cent Mac i l'u coma tres per cent Linux.",
    "sentenceIds": [
      "3bbf67e2e9000407f82c06747d512273f6c384026fd5ea257e05541bec210ac0"
    ]
  },
  {
    "id": "cv26-32eb63d04c5a1dc6",
    "text": "A escala mundial les darreres xifres són de cent tretze mil cinc-cents setanta-cinc casos confirmats i tres mil nou-cents noranta-cinc morts.",
    "sentenceIds": [
      "be6e6cd1b41bf3de5567495e635473127ee370fd76092e38d980b432342314f4"
    ]
  },
  {
    "id": "cv26-99e49ea8a8f702f0",
    "text": "Wood era un batedor dretà que també jugaba a bitlles part del temps, però va fer principalment de wicketkeeper.",
    "sentenceIds": [
      "e1507103433ab0579c377395d23922959cfb93669c74d1aef5bcb6ee085a916f"
    ]
  },
  {
    "id": "cv26-90cdf6bc21c92f37",
    "text": "La primera versió del navegador Firefox ha tingut dos milions i mig de descàrregues durant els dos primers dies.",
    "sentenceIds": [
      "586bba6a1be3cda17ccc52a587df14c7339c8f273b453ca7d0e76d5ad3208353"
    ]
  },
  {
    "id": "cv26-6fe9bfd4577f5b1d",
    "text": "Les estrelles supergegants són estrelles evolucionades amb una gran quantitat de massa, i són més grans i lluminoses que les estrelles de seqüència principal.",
    "sentenceIds": [
      "4a898218ab9f644f5395d9639946e75a947dd6a7d913f8e67c5287e009e8c891"
    ]
  },
  {
    "id": "cv26-7f60a12023ec83e4",
    "text": "Donar publicitat per mitjans telemàtics de la present resolució, la qual podrà consultar-se a la web municipal.",
    "sentenceIds": [
      "480bc42f0271fee34d1ba7a7d1689b2ee52269c59d1a7e00cebb8365cc617695"
    ]
  },
  {
    "id": "cv26-012957227e130994",
    "text": "Esquerra Republicana de Catalunya no descarta cap camí \"democràtic\" i \"pacífic\" per a aconseguir la independència.",
    "sentenceIds": [
      "8eb4b90abc17b3b3a77c8f9a3b3a0ded1c7ad395e5f2605149050f9cfbd21266"
    ]
  },
  {
    "id": "cv26-32996e74211bacd3",
    "text": "Mira'm quina és la millor manera d'anar de la camí de Santa Creu d'Olorda a Vallvidrera al passatge del Doctor Torres.",
    "sentenceIds": [
      "0e765d467f49d1d65e01c2d748e25f5ce9eb47908e2d3189cc481c0e8733e9b3"
    ]
  },
  {
    "id": "cv26-9f56544d7c4744bb",
    "text": "Mentrestant, l'Internet Explorer anava guanyant quota de mercat i s'anava consolidant com el navegador més popular a Internet.",
    "sentenceIds": [
      "6055005da5e64eedc66e0046457dd3b27e9cb3e96f1c93fae78c423ddf0fa287"
    ]
  },
  {
    "id": "cv26-190dcec8e8a0aea8",
    "text": "Quant al cost, qualsevol programari lliure es pot vendre, sempre que es respectin les llibertats originals que el defineixen.",
    "sentenceIds": [
      "8552714d692f085a0338aa1a9f7cfe44bbb23cd4fd6fab8459032013f57c5a23"
    ]
  },
  {
    "id": "cv26-1a1bb47a512d4157",
    "text": "Josep Fèlix Pons i Alonso va ser un periodista esportiu i actor de doblatge nascut a l'Hospitalet de Llobregat.",
    "sentenceIds": [
      "4955af316e398cf2b96f6faa999423e0e94b1ac8aa6e53e545ed8d227d4c2ae6"
    ]
  },
  {
    "id": "cv26-98d4a1ce36086f6b",
    "text": "L'any dos mil huit es preveu que el consum siga d'uns vint mil huit-cents metres cúbics, de cada tona produïda consumix uns huitanta-tres litres d'aigua.",
    "sentenceIds": [
      "94d8f07b3df9a965e3da3921eb0dce03536bf38384e1aac05592f893cd12ce86"
    ]
  },
  {
    "id": "cv26-e8db4e1f25656e57",
    "text": "Mira'm quina és la millor manera d'anar del carrer d'Alexandre de Torrelles al carrer de Santa Caterina de Siena.",
    "sentenceIds": [
      "40669603787224d50279b5742ae6560c6d7e75a6b730065746ba450d81bf69b8"
    ]
  },
  {
    "id": "cv26-f104dd9200a149a0",
    "text": "Rússia, amb vuit milions sis-cents trenta-tres mil sis-cents quaranta-tres casos i dos-cents quaranta-dos mil seixanta morts.",
    "sentenceIds": [
      "cb60df13a4d17608439abf9420de2168f8d0489ceead6dccbdf78fc52a19a335"
    ]
  },
  {
    "id": "cv26-b426c4b7b42df1b7",
    "text": "Antoni Maria Aragó i Cabañas va ser un historiador, arxiver, poeta, traductor i professor nascut a Lloret de Mar.",
    "sentenceIds": [
      "89a95451769f6b36f8cb30daf4617d60aea693d204085b8564b80d13a3bab127"
    ]
  },
  {
    "id": "cv26-c54c2e226f17eaa4",
    "text": "Els glossopteris van ser, així, uns de les principals víctimes de l'esdeveniment d'extinció massiva de finals del permià.",
    "sentenceIds": [
      "1461dc393a877944fd1fa13de018957e7637fe40fbd6bf5ff72a204d1000293e"
    ]
  },
  {
    "id": "cv26-bd39817f31b8f8bf",
    "text": "Regne Unit, amb vuit milions vuit-cents noranta-set mil cent quaranta-nou casos i cent quaranta mil quaranta-un morts.",
    "sentenceIds": [
      "c8c657322722eef17647f111f33ad99514a8778e96f9c02dfdb3398108ca6784"
    ]
  },
  {
    "id": "cv26-7773c0d4b7af04c2",
    "text": "El destí de les assignacions econòmiques concedides no podrà alterar-se en cap cas per la persona beneficiària.",
    "sentenceIds": [
      "800b92c332e17b6b84a45c6ca8abb516a6659004f6f4aa6a59a60bc35a5fb3c1"
    ]
  },
  {
    "id": "cv26-514cbcf350d183cd",
    "text": "Els matins són més avorrits que les tardes, les tardes més avorrides que les nits i les nits més avorrides que els matins.",
    "sentenceIds": [
      "927e1ede79d4b15cc74c69663928da4400828dde606cc10b7d1a30907bd7b21e"
    ]
  },
  {
    "id": "cv26-de0a9601d1e76575",
    "text": "Les acadèmies són escoles de gran capacitat establertes amb el patrocini de grups de negocis, de fe o voluntaris.",
    "sentenceIds": [
      "e0116e8c2bdbff540a88061686a2767368efc7188928f2ce71bee7113e951299"
    ]
  },
  {
    "id": "cv26-ad36ce722a1df2ab",
    "text": "Només el tres coma tres per cent dels pacients que pertanyen a aquest grup necessiten assistència respiratòria.",
    "sentenceIds": [
      "37c2bf430f4b59245736e04d62966ff26f97175a29d5c6f2b6137f407f08cbb6"
    ]
  },
  {
    "id": "cv26-98abfbfcd955ddac",
    "text": "Antoni Agramont i Quintana va ser un compositor, director i fiscornist de sardanes nascut a Castelló d'Empúries.",
    "sentenceIds": [
      "bb45fdddbe776cd7f7670617ca4c02a4935bb37a010aecf0032562e1e09b3ac6"
    ]
  },
  {
    "id": "cv26-2826fc80b1d89449",
    "text": "La conscienciació de tots els operaris perquè es facin servei en primer lloc els productes que caduquin abans.",
    "sentenceIds": [
      "7034e7c60473b0c8bcba05b41b7670af3a2b5a999ea024ea78d94e531b6c539e"
    ]
  },
  {
    "id": "cv26-485feda3f188f120",
    "text": "La propietat de l'edificació comporta associat el dret d'utilitzar la superfície del subsòl per al mateix edifici.",
    "sentenceIds": [
      "23ec5f2808094d11c19960c2206a56b7514d53981b61acaf57cf1540424cf60a"
    ]
  },
  {
    "id": "cv26-4f4dc989d096691d",
    "text": "Si vols parlar amb nosaltres des de l'estranger, truca al trenta-quatre noranta-tres cinc-cents quaranta-set vuitanta-vuit seixanta.",
    "sentenceIds": [
      "1fc442779a4b5f9478d712945ec06a7385e784dbc6cad5f6e40b0639ea471caf"
    ]
  },
  {
    "id": "cv26-aafb657f45704411",
    "text": "Rússia, amb set milions quatre-cents seixanta-quatre mil set-cents vuit casos i dos-cents cinc mil cinc-cents trenta-un morts.",
    "sentenceIds": [
      "a464a477a1fe916830efc696ce26a2c41de1ff48469a13eb4d9b69d27937b880"
    ]
  },
  {
    "id": "cv26-c7792c72d807d4d8",
    "text": "I a mi em recorda, és clar que amb la boira de la perspectiva, una curiosa ressemblança amb les serventes fidels.",
    "sentenceIds": [
      "bfcbc64d5993a42fae2dffa44a82eb36a935e54f245cd2e6c79d92e6603df12b"
    ]
  },
  {
    "id": "cv26-600c94e6b65f6508",
    "text": "El meu pare té dos telèfons: el sis-cents set zero setanta-quatre quatre-cents quaranta-tres i el sis-cents cinquanta-quatre setanta-sis cinquanta-quatre trenta-set.",
    "sentenceIds": [
      "16425569d87632c2193cafe3f50f087efe8cb7c17081c9e77ce858a3d84b05d1"
    ]
  },
  {
    "id": "cv26-c5910d2adb991bba",
    "text": "Al capdavall, les idees, immaterials com són, no tenien amo, i tampoc en el sentit que hom li ha donat després.",
    "sentenceIds": [
      "7d5edd585759f77eecba7f0afb9011e71bd7908838063387661f1a51b17d8af7"
    ]
  },
  {
    "id": "cv26-0cdec51cf83b26cd",
    "text": "Mira'm quina és la millor manera d'anar del carrer de la Reina Cristina al passatge Mare de Déu de l'Estrella.",
    "sentenceIds": [
      "639ad4639c6ab462c5667cac2368e18ca5d6ba00b9376028c29f1d376be1c987"
    ]
  },
  {
    "id": "cv26-8f2cbb0d2b1832b7",
    "text": "Va ser enterrat a la catedral de Viterbo, però la seva tomba fou destruïda durant les tasques de renovació del segle setze.",
    "sentenceIds": [
      "910e512cb5b3e31dd3acac083a8b238738f349dab3a7b0c84f3f8742a2d728da"
    ]
  },
  {
    "id": "cv26-70530dbc78275c9a",
    "text": "Dídac Vilà i Moragues va ser un compositor, director d'orquestra, contrabaixista i polític nascut a Cornellà de Llobregat.",
    "sentenceIds": [
      "7115c80fe46fee79d937b8cd5c7b45ffa619b3ed12567c9c724a1ebe48652460"
    ]
  },
  {
    "id": "cv26-63e1dc5e547af098",
    "text": "Quina és la millor manera d'anar del carrer de la Madriguera al camí Vell de Santa Creu d'Olorda a Vallvidrera?",
    "sentenceIds": [
      "f3d931794376601d6fba654ee6e9f49ef2460fbe7e897d3a6e42e4c35a45032f"
    ]
  },
  {
    "id": "cv26-7b52b51d3143e18f",
    "text": "Al llarg del dos mil quinze s'han baixat quatre-centes vint-i-nou cent vuitantat-tres còpies de programes en català des del nostre lloc web.",
    "sentenceIds": [
      "d7668def083a750fafa4288d510f45f7fd168dd8573ede7e7a9068d4c08626ae"
    ]
  },
  {
    "id": "cv26-9f4f180a114bad50",
    "text": "Emma Maleras i Gobern va ser una ballarina, coreògrafa, concertista i professora de castanyoles nascuda a Ripollet.",
    "sentenceIds": [
      "2e275ad843b76b0f3b5682629ffa1c33ac3d9a0cf7d032ebd6fdb33dd6308229"
    ]
  },
  {
    "id": "cv26-123770163a497777",
    "text": "Els meus amics han eixit amb les famílies, i jo no tinc a ningú en aquest món; estic sol..., completament sol.",
    "sentenceIds": [
      "3efe6931dcf71cc1ec7fc297e4cb9293ab548eabc29e35a2d51e77e197000455"
    ]
  },
  {
    "id": "cv26-7b90a9f2d6c341a8",
    "text": "Regne Unit, amb deu milions vint-i-un mil quatre-cents noranta-set casos i cent quaranta-quatre mil quatre-cents trenta-tres morts.",
    "sentenceIds": [
      "5a3bab8ca480056899c3f4340dca8fc188e28ee72530e7fb74b686a70c6053ff"
    ]
  },
  {
    "id": "cv26-a3a782df53d74819",
    "text": "Mira'm quina és la millor manera d'anar del carrer del Torrent de Can Mariner al carrer de les Naus de La Maquinista.",
    "sentenceIds": [
      "69645083afd7c607631e1b88b0552fcc2c4eb7bae67b90e9af0826a8297f8701"
    ]
  },
  {
    "id": "cv26-6a9c7a368b98ecdb",
    "text": "Temíem potser un fantasiós domini de les màquines i de la racionalitat per sobre dels nostres somnis i fantasies.",
    "sentenceIds": [
      "6e22ae2275d5a52d28ff0bfcfc6bfc54905351298efd18f9d99ba1f63ec12290"
    ]
  },
  {
    "id": "cv26-de1f9526ab4409cc",
    "text": "Als processats per malversació, els ha imposat una fiança solidària de cinc milions vuit-cents tres mil seixanta-vuit coma vuitanta-set euros.",
    "sentenceIds": [
      "17fa6e33800250773c2462ff82010cf4ae97bb46d279ab1fee16f88be405fbd4"
    ]
  },
  {
    "id": "cv26-65cdc3aee07c91b6",
    "text": "El món universitari ha tingut un paper molt destacat en el desenvolupament d'Internet i del programari lliure.",
    "sentenceIds": [
      "c30a6cc6d74d63eec30335eadc342613c8a0a4e81e6d1594ca3d301cf95e1578"
    ]
  },
  {
    "id": "cv26-e426d3ef9edfa7d4",
    "text": "El llaurador s'adormí i per segona vegada anaren els veïns a buscar-lo, ara més tranquils i una mica enfadats.",
    "sentenceIds": [
      "f77ed22174a8605ba60829b6f0cbdd2824321549c4a3994aeb727877dc5fa2d4"
    ]
  },
  {
    "id": "cv26-06a807efb37b7e63",
    "text": "La fase d'oficial bàsic (Basic Officer) acaba amb la selecció de la branca i la fase de transició a la fase intermèdia.",
    "sentenceIds": [
      "4a9a145ffe47af3555d506fb2c4a949335fe28b04f266212d3ad740b0b302fcc"
    ]
  },
  {
    "id": "cv26-c8b4fe1c092692f8",
    "text": "S'introdueixen regles noves i es milloren les existents, de manera que avui dia treballa amb més de dos mil sis-centes regles.",
    "sentenceIds": [
      "badb07f20e9c6b7c704c2fd32b5ac2ca6c4ddebfc07562804c374cc8450f0491"
    ]
  },
  {
    "id": "cv26-e17727e21a153488",
    "text": "Computer Gaming World va afirmar: \"Aquest joc ha estat dissenyat expressament per als jugadors experts de Wirzardry\".",
    "sentenceIds": [
      "39b9689ac8b3cd92f5b7986a7455f3fbce7ef6c1585202124b920ed4f32f82fa"
    ]
  },
  {
    "id": "cv26-48536eb425850d41",
    "text": "Regne Unit, amb nou milions sis-cents setanta-cinc mil cinquanta-vuit casos i cent quaranta-tres punt un tres sis zero morts.",
    "sentenceIds": [
      "4138be7a65250c91c90aca2d0b5230fe0d14a12c066d5e12b8d002bb8e074ada"
    ]
  },
  {
    "id": "cv26-b601e6a0648dc3fa",
    "text": "Avui dia, Linux és l'únic sistema operatiu que està disponible per a tots els sistemes que comercialitza l'empresa.",
    "sentenceIds": [
      "8e6c789394d763712ea1dc83212ab961197f0174806c7ddc4a23babc20d93c90"
    ]
  },
  {
    "id": "cv26-8de7f9ae23cfdfe0",
    "text": "El present encàrrec no es podrà modificar, allargar o esmenar si no és a través d'acord escrit entre les parts.",
    "sentenceIds": [
      "1777bb874f7203875f2b1f9e13cbec38621795669d4ea5f7ec9bdb3d6a44a421"
    ]
  },
  {
    "id": "cv26-c5bb129ebb87e1ef",
    "text": "S'escampava sobre l'Albufera una llum freda i blavosa, que donava a la seua superfície el dur reflex de l'acer.",
    "sentenceIds": [
      "5a9db0dfafaef02bef46e1cf4afac149eabf596d33b4cf8a998051f0414212e4"
    ]
  },
  {
    "id": "cv26-6d9d9b8d1782177a",
    "text": "Mira'm quina és la millor manera d'anar dels jardins de Maria Àngels Anglada i d'Abadal al carrer del Degà Bahí.",
    "sentenceIds": [
      "2aa12c30092f8e8d3ce09def14eae96efae8601bdb247da7bac906b1248d2d15"
    ]
  },
  {
    "id": "cv26-e09d8dda4ee389a6",
    "text": "Ara t'enviaré una imatge meua i així podràs fer-te una idea exacta de com són els habitants d'altres galàxies.",
    "sentenceIds": [
      "a40a4a115b14bbe8b6fbbcec02b71b38465b87e321dbe94dc12e2f76a1721b1a"
    ]
  },
  {
    "id": "cv26-d5bc3cb73ffd8549",
    "text": "La distància màxima des del marge fins a la darrera fila de plantes conreades no podrà ser superior a dos-cents metres.",
    "sentenceIds": [
      "9e712841f7e9a8c89c8e9b47d8694eaba76a4ff07d468a1d3d875e85852cee37"
    ]
  },
  {
    "id": "cv26-56846e19942b975a",
    "text": "Tot i que es trobava prostrat al llit, va continuar executant el seu imperi criminal fins que Dagger gairebé el mata.",
    "sentenceIds": [
      "f9513a428691a1d0a447defd7e03607af70334b19f54e9e57a4b9290249cac9c"
    ]
  },
  {
    "id": "cv26-5c02a1e7af895b9c",
    "text": "No m'agradaria acabar sense fer una petita conclusió sobre el programari lliure, el seu impacte en el nostre entorn, i el seu futur més immediat.",
    "sentenceIds": [
      "6f410879f33c604e062ac8f7c1dbf4d1af90b1cc39faa50e34a167ae4feace2a"
    ]
  },
  {
    "id": "cv26-44cf4203129648fc",
    "text": "Francesc Nel·lo i Ventosa va ser un ninotaire, dibuixant, escenògraf, interiorista i restaurador nascut a Tarragona.",
    "sentenceIds": [
      "5c6caaa89d0442e58aadfeeee4f8678cae04c30da75f86f7757ec0a9eeb5d5b1"
    ]
  },
  {
    "id": "cv26-dd5313ec1eda265d",
    "text": "El seu Paper Group treballa amb arxius i biblioteques en la conservació i restauració de les seves col·leccions.",
    "sentenceIds": [
      "3882b973e4461c9df26ea0ba9e5973f5e9e2b08726fd80d10512ee8e80601ff3"
    ]
  },
  {
    "id": "cv26-6aaa8c019607eca8",
    "text": "Qualsevol pot col·laborar en el projecte, bé escrivint articles nous, o bé corregint i ampliant els que ja hi ha.",
    "sentenceIds": [
      "35230c9bcd46b2463436a1d8ac00b1356f26d3e21e76dc2d9d09c201d5ce0e75"
    ]
  },
  {
    "id": "cv26-886138b8c83f6135",
    "text": "Mira'm quina és la millor manera d'anar del carrer dels Safareigs al carrer de la Santíssima Trinitat del Mont.",
    "sentenceIds": [
      "809eec19ed9ab23ff9165b231985907cb34f352695e378d196b059a5b65ccdd5"
    ]
  },
  {
    "id": "cv26-dd9e12473e2c6585",
    "text": "Algunes fan que s'augmenti el rendiment fins a un cinquanta per cent, com es pot llegir en aquest article en anglès.",
    "sentenceIds": [
      "a42a64008f4f4ae7d8d1304d1afe7da620860cd51daac42de30ea331f3aebb56"
    ]
  },
  {
    "id": "cv26-478a1c5c18e3d872",
    "text": "Regne Unit, amb onze milions cinc-cents quaranta-dos mil cent quaranta-tres casos i cent quaranta-set mil quatre-cents trenta-tres morts.",
    "sentenceIds": [
      "334cac0f557bbbf980681347e1f2db5364bd1c3780e7447da50d0b51c44cb69c"
    ]
  },
  {
    "id": "cv26-d2be22d96f001db2",
    "text": "L'Anna ens va presentar una primera versió de l'arbre de continguts durant la trobada anual del dos mil catorze.",
    "sentenceIds": [
      "b143e06593a38237fff9945b2bcc9b939096cba4edc5d21bac26c3d1df6128ee"
    ]
  },
  {
    "id": "cv26-fa4c2e296a5e5dff",
    "text": "Més tard aquell mateix any, va guanyar als punts el boxejador olímpic Art Binkowski, que no havia conegut encara la derrota.",
    "sentenceIds": [
      "54a00c929902160f9f544b4198a8ef2b5dfca3c2d9bf477c0cbe790e3470c611"
    ]
  },
  {
    "id": "cv26-6a527d5dd8ae9d0a",
    "text": "La reacció immediata de les discogràfiques i d'alguns grups musicals fou perseguir legalment el fenomen de la forma més contundent possible.",
    "sentenceIds": [
      "d178617f30ee3be1ce84d6ee6df42f6570c30d682f35442bb87d72c4abfa9be0"
    ]
  }
]
;
